import { query, mutation, internalMutation } from "./_generated/server";
import { v } from "convex/values";
import { Id } from "./_generated/dataModel";

// ═════════════════════════════════════════════════════════════
// Timeline Event Logger — called from other mutations
// ═════════════════════════════════════════════════════════════

export const logEvent = internalMutation({
  args: {
    userId: v.id("users"),
    homeId: v.id("homes"),
    systemId: v.optional(v.id("systems")),
    eventType: v.string(),
    title: v.string(),
    description: v.optional(v.string()),
    icon: v.string(),
    color: v.string(),
    linkedTaskId: v.optional(v.id("scheduledMaintenance")),
    linkedServiceRequestId: v.optional(v.id("serviceRequests")),
    linkedDocumentId: v.optional(v.id("vaultDocuments")),
    linkedReceiptId: v.optional(v.id("serviceReceipts")),
    cost: v.optional(v.number()),
    costType: v.optional(v.string()),
    performedBy: v.optional(v.string()),
    metadata: v.optional(v.any()),
  },
  handler: async (ctx, args) => {
    return await ctx.db.insert("timelineEvents", {
      userId: args.userId,
      homeId: args.homeId,
      systemId: args.systemId,
      eventType: args.eventType,
      title: args.title,
      description: args.description,
      icon: args.icon,
      color: args.color,
      linkedTaskId: args.linkedTaskId,
      linkedServiceRequestId: args.linkedServiceRequestId,
      linkedDocumentId: args.linkedDocumentId,
      linkedReceiptId: args.linkedReceiptId,
      cost: args.cost,
      costType: args.costType,
      performedBy: args.performedBy,
      isUserGenerated: args.performedBy !== "system",
      isAutoGenerated: args.performedBy === "system",
      metadata: args.metadata,
      timestamp: Date.now(),
    });
  },
});

// ═════════════════════════════════════════════════════════════
// Queries
// ═════════════════════════════════════════════════════════════

export const getTimeline = query({
  args: {
    homeId: v.id("homes"),
    limit: v.optional(v.number()),
    eventType: v.optional(v.string()),
  },
  handler: async (ctx, args) => {
    const limit = args.limit ?? 50;

    if (args.eventType) {
      const events = await ctx.db
        .query("timelineEvents")
        .withIndex("by_homeId", (q) => q.eq("homeId", args.homeId))
        .order("desc")
        .take(limit * 3);

      return events
        .filter((e) => e.eventType === args.eventType)
        .slice(0, limit);
    }

    return await ctx.db
      .query("timelineEvents")
      .withIndex("by_homeId_timestamp", (q) => q.eq("homeId", args.homeId))
      .order("desc")
      .take(limit);
  },
});

export const getTimelineByMonth = query({
  args: {
    homeId: v.id("homes"),
    year: v.number(),
    month: v.number(),
  },
  handler: async (ctx, args) => {
    const startOfMonth = new Date(args.year, args.month - 1, 1).getTime();
    const endOfMonth = new Date(args.year, args.month, 0, 23, 59, 59).getTime();

    const events = await ctx.db
      .query("timelineEvents")
      .withIndex("by_homeId_timestamp", (q) =>
        q.eq("homeId", args.homeId).gte("timestamp", startOfMonth).lte("timestamp", endOfMonth)
      )
      .order("desc")
      .take(200);

    return events;
  },
});

export const getTimelineStats = query({
  args: {
    homeId: v.id("homes"),
    year: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const year = args.year ?? new Date().getFullYear();
    const startOfYear = new Date(year, 0, 1).getTime();
    const endOfYear = new Date(year, 11, 31, 23, 59, 59).getTime();

    const events = await ctx.db
      .query("timelineEvents")
      .withIndex("by_homeId_timestamp", (q) =>
        q.eq("homeId", args.homeId).gte("timestamp", startOfYear).lte("timestamp", endOfYear)
      )
      .take(500);

    const tasksCompleted = events.filter(
      (e) => e.eventType === "task_completed",
    ).length;
    const totalSpent = events
      .filter((e) => e.cost && e.cost > 0)
      .reduce((sum, e) => sum + (e.cost ?? 0), 0);
    const diySavings = events
      .filter((e) => e.costType === "diy_savings")
      .reduce((sum, e) => sum + (e.cost ?? 0), 0);

    const byType: Record<string, number> = {};
    for (const e of events) {
      byType[e.eventType] = (byType[e.eventType] ?? 0) + 1;
    }

    return {
      year,
      totalEvents: events.length,
      tasksCompleted,
      totalSpent: Math.round(totalSpent),
      diySavings: Math.round(diySavings),
      byType,
    };
  },
});

export const getSystemTimeline = query({
  args: {
    systemId: v.id("systems"),
    limit: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    return await ctx.db
      .query("timelineEvents")
      .withIndex("by_systemId", (q) => q.eq("systemId", args.systemId))
      .order("desc")
      .take(args.limit ?? 50);
  },
});

// ═════════════════════════════════════════════════════════════
// User-created timeline events (manual entries)
// ═════════════════════════════════════════════════════════════

export const addManualEvent = mutation({
  args: {
    homeId: v.id("homes"),
    systemId: v.optional(v.id("systems")),
    eventType: v.string(),
    title: v.string(),
    description: v.optional(v.string()),
    cost: v.optional(v.number()),
    costType: v.optional(v.string()),
    performedBy: v.optional(v.string()),
    date: v.optional(v.number()),
  },
  handler: async (ctx, args) => {
    const identity = await ctx.auth.getUserIdentity();
    if (!identity) throw new Error("Not authenticated");

    const user = await ctx.db
      .query("users")
      .withIndex("email", (q) => q.eq("email", identity.email!))
      .first();
    if (!user) throw new Error("User not found");

    const iconMap: Record<string, string> = {
      service_call: "🔧",
      task_completed: "✅",
      system_added: "➕",
      system_replaced: "🔄",
      document_uploaded: "📄",
      receipt_uploaded: "🧾",
      cost_recorded: "💰",
      note: "📝",
    };

    const colorMap: Record<string, string> = {
      service_call: "amber",
      task_completed: "green",
      system_added: "teal",
      system_replaced: "blue",
      document_uploaded: "gray",
      receipt_uploaded: "gray",
      cost_recorded: "emerald",
      note: "gray",
    };

    return await ctx.db.insert("timelineEvents", {
      userId: user._id,
      homeId: args.homeId,
      systemId: args.systemId,
      eventType: args.eventType,
      title: args.title,
      description: args.description,
      icon: iconMap[args.eventType] ?? "📝",
      color: colorMap[args.eventType] ?? "gray",
      cost: args.cost,
      costType: args.costType,
      performedBy: args.performedBy,
      isUserGenerated: true,
      isAutoGenerated: false,
      timestamp: args.date ?? Date.now(),
    });
  },
});
