// System Catalog Seed Data — Interior, Appliance, Safety, Structural, Landscape
// Weibull parameters calibrated from NAHB life expectancy studies, manufacturer data,
// home inspection records, and ASHRAE references.

interface DataField {
  fieldName: string;
  fieldType: "select" | "text" | "number" | "boolean";
  options?: string[];
  required: boolean;
  inspectorField: boolean;
  homeownerField: boolean;
}

interface RegionalFactor {
  region: string;
  adjustmentFactor: number;
  reason: string;
}

interface CatalogEntry {
  catalogId: string;
  category: string;
  subcategory: string;
  systemName: string;
  trackingLevel: "major_system" | "component" | "fixture" | "material" | "cosmetic";
  visibleToHomeowner: boolean;
  inspectorOnly: boolean;
  expectedLifeYears: { low: number; median: number; high: number };
  weibullShape: number;
  weibullScale: number;
  regionalFactors?: RegionalFactor[];
  replacementCost: { low: number; median: number; high: number };
  dataFields?: DataField[];
  maintenanceTaskIds: string[];
  iotCompatible?: boolean;
  iotDeviceTypes?: string[];
  careKitProductTypes?: string[];
  isActive: boolean;
  lastUpdated: number;
}

// ============================================================
// INTERIOR (20 entries)
// ============================================================

export const INTERIOR_CATALOG: CatalogEntry[] = [
  {
    catalogId: "interior.flooring.hardwood",
    category: "interior",
    subcategory: "flooring",
    systemName: "Flooring — Hardwood",
    trackingLevel: "material",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 20, median: 50, high: 75 },
    weibullShape: 2.5,
    weibullScale: 55,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.85, reason: "Humidity-driven expansion/contraction and cupping in Gulf Coast homes without good HVAC control" },
      { region: "cold_harsh", adjustmentFactor: 0.90, reason: "Winter dry air causes gapping; salt/sand tracked in wears finish faster" },
      { region: "marine", adjustmentFactor: 0.80, reason: "Persistent moisture near coast accelerates finish breakdown" },
    ],
    replacementCost: { low: 3000, median: 8000, high: 18000 },
    dataFields: [
      { fieldName: "wood_species", fieldType: "select", options: ["Oak", "Maple", "Hickory", "Cherry", "Walnut", "Bamboo", "Pine", "Other"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "finish", fieldType: "select", options: ["Site-finished polyurethane", "Pre-finished", "Oil", "Wax", "Unfinished"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "rooms", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "approximate_sqft", fieldType: "number", required: false, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.hardwood.refinish", "task.interior.hardwood.clean", "task.interior.hardwood.inspect_finish"],
    careKitProductTypes: ["hardwood_cleaner", "microfiber_mop", "felt_pads"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.flooring.lvp",
    category: "interior",
    subcategory: "flooring",
    systemName: "Flooring — Luxury Vinyl Plank (LVP)",
    trackingLevel: "material",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 10, median: 18, high: 25 },
    weibullShape: 2.8,
    weibullScale: 20,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.95, reason: "LVP handles humidity well; minor concern with adhesive breakdown under sustained heat in unconditioned spaces" },
    ],
    replacementCost: { low: 2000, median: 5000, high: 12000 },
    dataFields: [
      { fieldName: "wear_layer_mil", fieldType: "number", required: false, inspectorField: true, homeownerField: false },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "rooms", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "approximate_sqft", fieldType: "number", required: false, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.lvp.clean", "task.interior.lvp.inspect"],
    careKitProductTypes: ["vinyl_floor_cleaner", "microfiber_mop"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.flooring.laminate",
    category: "interior",
    subcategory: "flooring",
    systemName: "Flooring — Laminate",
    trackingLevel: "material",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 8, median: 15, high: 22 },
    weibullShape: 2.8,
    weibullScale: 17,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.80, reason: "Laminate core is very susceptible to moisture damage; swelling and delamination common in humid climates without AC control" },
    ],
    replacementCost: { low: 1500, median: 3500, high: 8000 },
    dataFields: [
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "rooms", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "approximate_sqft", fieldType: "number", required: false, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.laminate.clean", "task.interior.laminate.inspect"],
    careKitProductTypes: ["laminate_cleaner", "microfiber_mop"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.flooring.tile_ceramic",
    category: "interior",
    subcategory: "flooring",
    systemName: "Flooring — Ceramic Tile",
    trackingLevel: "material",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 20, median: 50, high: 75 },
    weibullShape: 2.0,
    weibullScale: 55,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.95, reason: "Tile itself is durable; grout degrades faster in high-humidity bathrooms" },
    ],
    replacementCost: { low: 2500, median: 6000, high: 15000 },
    dataFields: [
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "grout_condition", fieldType: "select", options: ["Sealed/Good", "Fair", "Cracked/Missing"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "rooms", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "approximate_sqft", fieldType: "number", required: false, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.tile.clean_grout", "task.interior.tile.reseal_grout", "task.interior.tile.inspect"],
    careKitProductTypes: ["grout_cleaner", "grout_sealer"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.flooring.tile_porcelain",
    category: "interior",
    subcategory: "flooring",
    systemName: "Flooring — Porcelain Tile",
    trackingLevel: "material",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 30, median: 55, high: 75 },
    weibullShape: 2.0,
    weibullScale: 60,
    replacementCost: { low: 3000, median: 8000, high: 20000 },
    dataFields: [
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "grout_condition", fieldType: "select", options: ["Sealed/Good", "Fair", "Cracked/Missing"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "rooms", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "approximate_sqft", fieldType: "number", required: false, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.tile.clean_grout", "task.interior.tile.reseal_grout", "task.interior.tile.inspect"],
    careKitProductTypes: ["grout_cleaner", "grout_sealer"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.flooring.carpet",
    category: "interior",
    subcategory: "flooring",
    systemName: "Flooring — Carpet",
    trackingLevel: "material",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 5, median: 10, high: 15 },
    weibullShape: 3.0,
    weibullScale: 11,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.80, reason: "Humidity drives mold/mildew in carpet pad; Gulf Coast homes often replace carpet with hard surfaces for this reason" },
    ],
    replacementCost: { low: 1200, median: 3000, high: 8000 },
    dataFields: [
      { fieldName: "fiber_type", fieldType: "select", options: ["Nylon", "Polyester", "Olefin", "Wool", "Triexta", "Unknown"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "rooms", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "approximate_sqft", fieldType: "number", required: false, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.carpet.vacuum", "task.interior.carpet.deep_clean", "task.interior.carpet.inspect"],
    careKitProductTypes: ["carpet_spot_cleaner", "carpet_deodorizer"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.flooring.epoxy",
    category: "interior",
    subcategory: "flooring",
    systemName: "Flooring — Epoxy",
    trackingLevel: "material",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 5, median: 12, high: 20 },
    weibullShape: 2.5,
    weibullScale: 14,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.85, reason: "Moisture vapor transmission through slab can cause delamination; concrete moisture testing essential before application" },
    ],
    replacementCost: { low: 1500, median: 3500, high: 7000 },
    dataFields: [
      { fieldName: "location", fieldType: "select", options: ["Garage", "Basement", "Utility room", "Other"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "approximate_sqft", fieldType: "number", required: false, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.epoxy.clean", "task.interior.epoxy.inspect"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.countertop.granite",
    category: "interior",
    subcategory: "countertops",
    systemName: "Countertops — Granite",
    trackingLevel: "material",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 30, median: 60, high: 100 },
    weibullShape: 1.8,
    weibullScale: 70,
    replacementCost: { low: 2000, median: 4500, high: 10000 },
    dataFields: [
      { fieldName: "edge_profile", fieldType: "select", options: ["Eased", "Beveled", "Bullnose", "Ogee", "Other"], required: false, inspectorField: false, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "location", fieldType: "select", options: ["Kitchen", "Bathroom", "Both", "Other"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.granite.seal", "task.interior.granite.clean"],
    careKitProductTypes: ["granite_sealer", "stone_cleaner"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.countertop.quartz",
    category: "interior",
    subcategory: "countertops",
    systemName: "Countertops — Quartz",
    trackingLevel: "material",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 25, median: 50, high: 75 },
    weibullShape: 1.8,
    weibullScale: 55,
    replacementCost: { low: 2500, median: 5500, high: 12000 },
    dataFields: [
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "location", fieldType: "select", options: ["Kitchen", "Bathroom", "Both", "Other"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.quartz.clean", "task.interior.quartz.inspect"],
    careKitProductTypes: ["stone_cleaner"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.countertop.marble",
    category: "interior",
    subcategory: "countertops",
    systemName: "Countertops — Marble",
    trackingLevel: "material",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 30, median: 60, high: 100 },
    weibullShape: 1.8,
    weibullScale: 70,
    replacementCost: { low: 3000, median: 7000, high: 15000 },
    dataFields: [
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "location", fieldType: "select", options: ["Kitchen", "Bathroom", "Both", "Other"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.marble.seal", "task.interior.marble.clean", "task.interior.marble.polish"],
    careKitProductTypes: ["marble_sealer", "stone_cleaner", "marble_polish"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.countertop.laminate",
    category: "interior",
    subcategory: "countertops",
    systemName: "Countertops — Laminate",
    trackingLevel: "material",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 10, median: 18, high: 25 },
    weibullShape: 2.8,
    weibullScale: 20,
    replacementCost: { low: 800, median: 1800, high: 3500 },
    dataFields: [
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "location", fieldType: "select", options: ["Kitchen", "Bathroom", "Both", "Other"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.laminate_counter.clean", "task.interior.laminate_counter.inspect_seams"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.countertop.butcher_block",
    category: "interior",
    subcategory: "countertops",
    systemName: "Countertops — Butcher Block",
    trackingLevel: "material",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 10, median: 20, high: 30 },
    weibullShape: 2.5,
    weibullScale: 22,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.85, reason: "Humidity causes warping and mold in wood countertops; frequent oiling required in Gulf Coast kitchens" },
    ],
    replacementCost: { low: 1200, median: 3000, high: 6000 },
    dataFields: [
      { fieldName: "wood_species", fieldType: "select", options: ["Maple", "Walnut", "Cherry", "Oak", "Teak", "Other"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.butcher_block.oil", "task.interior.butcher_block.sand_refinish"],
    careKitProductTypes: ["mineral_oil", "butcher_block_conditioner"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.paint.walls",
    category: "interior",
    subcategory: "Paint",
    systemName: "Interior Paint — Walls",
    trackingLevel: "cosmetic",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 3, median: 7, high: 12 },
    weibullShape: 3.0,
    weibullScale: 8,
    replacementCost: { low: 1500, median: 4000, high: 10000 },
    dataFields: [
      { fieldName: "paint_type", fieldType: "select", options: ["Flat/Matte", "Eggshell", "Satin", "Semi-gloss", "Gloss", "Unknown"], required: false, inspectorField: false, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.paint.touch_up", "task.interior.paint.repaint"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.tile.backsplash",
    category: "interior",
    subcategory: "tile",
    systemName: "Kitchen Backsplash Tile",
    trackingLevel: "material",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 20, median: 40, high: 60 },
    weibullShape: 2.0,
    weibullScale: 45,
    replacementCost: { low: 600, median: 1500, high: 4000 },
    dataFields: [
      { fieldName: "material", fieldType: "select", options: ["Ceramic", "Porcelain", "Glass", "Natural stone", "Metal", "Other"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.backsplash.clean_grout", "task.interior.backsplash.reseal"],
    careKitProductTypes: ["grout_cleaner", "grout_sealer"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.tile.shower_surround",
    category: "interior",
    subcategory: "tile",
    systemName: "Shower Tile Surround",
    trackingLevel: "material",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 15, median: 30, high: 50 },
    weibullShape: 2.5,
    weibullScale: 35,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.85, reason: "High humidity slows drying between uses; mold/mildew in grout lines is primary failure mode in Gulf Coast bathrooms" },
    ],
    replacementCost: { low: 2000, median: 5000, high: 12000 },
    dataFields: [
      { fieldName: "material", fieldType: "select", options: ["Ceramic", "Porcelain", "Natural stone", "Glass", "Other"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "grout_condition", fieldType: "select", options: ["Sealed/Good", "Fair", "Cracked/Missing"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.shower_tile.clean_grout", "task.interior.shower_tile.reseal_grout", "task.interior.shower_tile.recaulk"],
    careKitProductTypes: ["grout_cleaner", "grout_sealer", "silicone_caulk"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.cabinets.kitchen",
    category: "interior",
    subcategory: "Cabinets",
    systemName: "Kitchen Cabinets",
    trackingLevel: "material",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 15, median: 35, high: 50 },
    weibullShape: 2.2,
    weibullScale: 38,
    replacementCost: { low: 5000, median: 15000, high: 40000 },
    dataFields: [
      { fieldName: "material", fieldType: "select", options: ["Solid wood", "Plywood", "MDF", "Particle board", "Thermofoil"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "door_style", fieldType: "select", options: ["Shaker", "Raised panel", "Flat panel", "Beadboard", "Other"], required: false, inspectorField: false, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.cabinets.clean", "task.interior.cabinets.adjust_hinges", "task.interior.cabinets.inspect"],
    careKitProductTypes: ["wood_cabinet_cleaner", "hinge_lubricant"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.cabinets.bathroom",
    category: "interior",
    subcategory: "Cabinets",
    systemName: "Bathroom Vanity/Cabinets",
    trackingLevel: "material",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 12, median: 25, high: 40 },
    weibullShape: 2.2,
    weibullScale: 28,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.85, reason: "Bathroom moisture and humidity degrade particle board and MDF vanities faster in Gulf Coast homes" },
    ],
    replacementCost: { low: 500, median: 2000, high: 6000 },
    dataFields: [
      { fieldName: "material", fieldType: "select", options: ["Solid wood", "Plywood", "MDF", "Particle board", "Thermofoil"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.vanity.clean", "task.interior.vanity.inspect_moisture", "task.interior.vanity.recaulk"],
    careKitProductTypes: ["wood_cabinet_cleaner", "silicone_caulk"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.water_heater_closet",
    category: "interior",
    subcategory: "Utility",
    systemName: "Water Heater Closet/Pan",
    trackingLevel: "component",
    visibleToHomeowner: false,
    inspectorOnly: true,
    expectedLifeYears: { low: 20, median: 40, high: 60 },
    weibullShape: 1.5,
    weibullScale: 45,
    replacementCost: { low: 100, median: 300, high: 600 },
    dataFields: [
      { fieldName: "drain_pan_present", fieldType: "boolean", required: true, inspectorField: true, homeownerField: false },
      { fieldName: "drain_line_connected", fieldType: "boolean", required: true, inspectorField: true, homeownerField: false },
      { fieldName: "condition", fieldType: "select", options: ["Good", "Fair", "Poor", "Missing pan"], required: true, inspectorField: true, homeownerField: false },
    ],
    maintenanceTaskIds: ["task.interior.wh_closet.inspect_pan", "task.interior.wh_closet.check_drain"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.attic_access",
    category: "interior",
    subcategory: "Utility",
    systemName: "Attic Access/Scuttle",
    trackingLevel: "component",
    visibleToHomeowner: false,
    inspectorOnly: true,
    expectedLifeYears: { low: 30, median: 50, high: 75 },
    weibullShape: 1.5,
    weibullScale: 55,
    replacementCost: { low: 100, median: 300, high: 800 },
    dataFields: [
      { fieldName: "type", fieldType: "select", options: ["Scuttle hole", "Pull-down stairs", "Walk-up", "None"], required: true, inspectorField: true, homeownerField: false },
      { fieldName: "insulated", fieldType: "boolean", required: true, inspectorField: true, homeownerField: false },
      { fieldName: "weather_stripped", fieldType: "boolean", required: false, inspectorField: true, homeownerField: false },
    ],
    maintenanceTaskIds: ["task.interior.attic_access.inspect", "task.interior.attic_access.insulate"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "interior.fireplace_gas",
    category: "interior",
    subcategory: "fireplace",
    systemName: "Gas Fireplace",
    trackingLevel: "fixture",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 15, median: 20, high: 25 },
    weibullShape: 3.0,
    weibullScale: 22,
    replacementCost: { low: 2000, median: 4500, high: 8000 },
    dataFields: [
      { fieldName: "type", fieldType: "select", options: ["Vented", "Ventless/Vent-free", "Direct vent", "B-vent"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.interior.gas_fireplace.annual_service", "task.interior.gas_fireplace.clean_glass", "task.interior.gas_fireplace.inspect"],
    iotCompatible: true,
    iotDeviceTypes: ["smart_thermostat_fireplace"],
    isActive: true,
    lastUpdated: Date.now(),
  },
];

// ============================================================
// APPLIANCES (8 entries)
// ============================================================

export const APPLIANCE_CATALOG: CatalogEntry[] = [
  {
    catalogId: "appliance.refrigerator",
    category: "appliance",
    subcategory: "kitchen",
    systemName: "Refrigerator",
    trackingLevel: "major_system",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 10, median: 14, high: 20 },
    weibullShape: 3.0,
    weibullScale: 15,
    replacementCost: { low: 800, median: 2000, high: 5000 },
    dataFields: [
      { fieldName: "type", fieldType: "select", options: ["French door", "Side-by-side", "Top freezer", "Bottom freezer", "Built-in", "Mini/Compact"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "manufacturer", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "model_number", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.appliance.fridge.clean_coils", "task.appliance.fridge.replace_water_filter", "task.appliance.fridge.check_seals"],
    iotCompatible: true,
    iotDeviceTypes: ["smart_appliance_monitor", "leak_sensor"],
    careKitProductTypes: ["coil_brush", "refrigerator_water_filter"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "appliance.dishwasher",
    category: "appliance",
    subcategory: "kitchen",
    systemName: "Dishwasher",
    trackingLevel: "major_system",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 8, median: 12, high: 16 },
    weibullShape: 3.0,
    weibullScale: 12,
    replacementCost: { low: 400, median: 800, high: 2000 },
    dataFields: [
      { fieldName: "manufacturer", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "model_number", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.appliance.dishwasher.clean_filter", "task.appliance.dishwasher.clean_spray_arms", "task.appliance.dishwasher.inspect_hoses"],
    iotCompatible: true,
    iotDeviceTypes: ["smart_appliance_monitor", "leak_sensor"],
    careKitProductTypes: ["dishwasher_cleaner"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "appliance.washing_machine",
    category: "appliance",
    subcategory: "laundry",
    systemName: "Washing Machine",
    trackingLevel: "major_system",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 8, median: 11, high: 15 },
    weibullShape: 3.2,
    weibullScale: 12,
    replacementCost: { low: 500, median: 1000, high: 2500 },
    dataFields: [
      { fieldName: "type", fieldType: "select", options: ["Front load", "Top load", "Top load HE"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "manufacturer", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "model_number", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.appliance.washer.clean_drum", "task.appliance.washer.inspect_hoses", "task.appliance.washer.clean_filter"],
    iotCompatible: true,
    iotDeviceTypes: ["smart_appliance_monitor", "leak_sensor", "water_shutoff_valve"],
    careKitProductTypes: ["washing_machine_cleaner", "stainless_steel_hoses"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "appliance.dryer",
    category: "appliance",
    subcategory: "laundry",
    systemName: "Dryer",
    trackingLevel: "major_system",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 10, median: 13, high: 18 },
    weibullShape: 3.0,
    weibullScale: 14,
    replacementCost: { low: 500, median: 1000, high: 2500 },
    dataFields: [
      { fieldName: "fuel_type", fieldType: "select", options: ["Electric", "Gas"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "manufacturer", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "model_number", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.appliance.dryer.clean_lint_trap", "task.appliance.dryer.clean_vent_duct", "task.appliance.dryer.inspect_exhaust"],
    iotCompatible: true,
    iotDeviceTypes: ["dryer_vent_monitor"],
    careKitProductTypes: ["dryer_vent_brush_kit", "lint_trap_brush"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "appliance.range_gas",
    category: "appliance",
    subcategory: "kitchen",
    systemName: "Range/Oven (Gas)",
    trackingLevel: "major_system",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 12, median: 18, high: 25 },
    weibullShape: 2.8,
    weibullScale: 19,
    replacementCost: { low: 600, median: 1500, high: 5000 },
    dataFields: [
      { fieldName: "configuration", fieldType: "select", options: ["Freestanding", "Slide-in", "Drop-in", "Wall oven + cooktop"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "manufacturer", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "model_number", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.appliance.range_gas.clean_burners", "task.appliance.range_gas.check_igniter", "task.appliance.range_gas.inspect_gas_line"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "appliance.range_electric",
    category: "appliance",
    subcategory: "kitchen",
    systemName: "Range/Oven (Electric)",
    trackingLevel: "major_system",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 10, median: 15, high: 20 },
    weibullShape: 3.0,
    weibullScale: 16,
    replacementCost: { low: 500, median: 1200, high: 4000 },
    dataFields: [
      { fieldName: "cooktop_type", fieldType: "select", options: ["Coil", "Smooth-top radiant", "Induction"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "configuration", fieldType: "select", options: ["Freestanding", "Slide-in", "Drop-in", "Wall oven + cooktop"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "manufacturer", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "model_number", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.appliance.range_electric.clean_elements", "task.appliance.range_electric.inspect"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "appliance.microwave",
    category: "appliance",
    subcategory: "kitchen",
    systemName: "Microwave (Built-in)",
    trackingLevel: "fixture",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 7, median: 10, high: 15 },
    weibullShape: 3.2,
    weibullScale: 11,
    replacementCost: { low: 200, median: 500, high: 1200 },
    dataFields: [
      { fieldName: "type", fieldType: "select", options: ["Over-the-range", "Built-in", "Drawer"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "manufacturer", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.appliance.microwave.clean", "task.appliance.microwave.inspect_door_seal"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "appliance.range_hood",
    category: "appliance",
    subcategory: "kitchen",
    systemName: "Range Hood/Exhaust Fan",
    trackingLevel: "fixture",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 10, median: 15, high: 20 },
    weibullShape: 2.8,
    weibullScale: 16,
    replacementCost: { low: 200, median: 600, high: 2000 },
    dataFields: [
      { fieldName: "venting", fieldType: "select", options: ["Ducted exterior", "Recirculating", "Convertible", "Unknown"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "manufacturer", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.appliance.range_hood.clean_filter", "task.appliance.range_hood.clean_duct", "task.appliance.range_hood.inspect"],
    careKitProductTypes: ["degreaser", "range_hood_filters"],
    isActive: true,
    lastUpdated: Date.now(),
  },
];

// ============================================================
// SAFETY (4 entries)
// ============================================================

export const SAFETY_CATALOG: CatalogEntry[] = [
  {
    catalogId: "safety.smoke_detector",
    category: "safety",
    subcategory: "Fire Protection",
    systemName: "Smoke Detector",
    trackingLevel: "component",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 8, median: 10, high: 12 },
    weibullShape: 4.0,
    weibullScale: 10,
    replacementCost: { low: 15, median: 35, high: 80 },
    dataFields: [
      { fieldName: "type", fieldType: "select", options: ["Ionization", "Photoelectric", "Dual-sensor", "Smart/Connected", "Unknown"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "power_source", fieldType: "select", options: ["Hardwired with battery backup", "Battery only (10-year sealed)", "Battery only (replaceable)"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "interconnected", fieldType: "boolean", required: false, inspectorField: true, homeownerField: false },
      { fieldName: "quantity", fieldType: "number", required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.safety.smoke.test_monthly", "task.safety.smoke.replace_batteries", "task.safety.smoke.replace_unit"],
    iotCompatible: true,
    iotDeviceTypes: ["smart_smoke_detector"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "safety.co_detector",
    category: "safety",
    subcategory: "Gas Detection",
    systemName: "CO Detector",
    trackingLevel: "component",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 5, median: 7, high: 10 },
    weibullShape: 4.0,
    weibullScale: 7,
    replacementCost: { low: 20, median: 40, high: 80 },
    dataFields: [
      { fieldName: "power_source", fieldType: "select", options: ["Hardwired with battery backup", "Battery only (sealed)", "Battery only (replaceable)", "Plug-in"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "combo_unit", fieldType: "boolean", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "quantity", fieldType: "number", required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.safety.co.test_monthly", "task.safety.co.replace_batteries", "task.safety.co.replace_unit"],
    iotCompatible: true,
    iotDeviceTypes: ["smart_co_detector"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "safety.fire_extinguisher",
    category: "safety",
    subcategory: "Fire Protection",
    systemName: "Fire Extinguisher",
    trackingLevel: "component",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 5, median: 8, high: 12 },
    weibullShape: 2.5,
    weibullScale: 9,
    replacementCost: { low: 20, median: 50, high: 100 },
    dataFields: [
      { fieldName: "type", fieldType: "select", options: ["ABC dry chemical", "Kitchen (Class K)", "CO2", "Water"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "size", fieldType: "select", options: ["2.5 lb", "5 lb", "10 lb"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "quantity", fieldType: "number", required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.safety.extinguisher.check_pressure", "task.safety.extinguisher.inspect", "task.safety.extinguisher.replace"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "safety.radon_mitigation",
    category: "safety",
    subcategory: "Air Quality",
    systemName: "Radon Mitigation System",
    trackingLevel: "major_system",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 15, median: 25, high: 40 },
    weibullShape: 2.5,
    weibullScale: 27,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 1.0, reason: "Radon varies by geology, not climate; Florida panhandle has mixed radon potential" },
      { region: "cold_harsh", adjustmentFactor: 1.0, reason: "Radon is common in northern climates; system life not climate-dependent" },
    ],
    replacementCost: { low: 800, median: 1500, high: 3000 },
    dataFields: [
      { fieldName: "type", fieldType: "select", options: ["Sub-slab depressurization (active)", "Sub-membrane (crawlspace)", "Passive stack"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "fan_location", fieldType: "select", options: ["Attic", "Exterior wall", "Garage", "Other"], required: false, inspectorField: true, homeownerField: false },
      { fieldName: "u_tube_manometer_present", fieldType: "boolean", required: true, inspectorField: true, homeownerField: false },
    ],
    maintenanceTaskIds: ["task.safety.radon.check_manometer", "task.safety.radon.test_levels", "task.safety.radon.inspect_fan"],
    iotCompatible: true,
    iotDeviceTypes: ["radon_monitor"],
    isActive: true,
    lastUpdated: Date.now(),
  },
];

// ============================================================
// STRUCTURAL (4 entries)
// ============================================================

export const STRUCTURAL_CATALOG: CatalogEntry[] = [
  {
    catalogId: "structural.foundation.slab",
    category: "structural",
    subcategory: "foundation",
    systemName: "Foundation — Slab on Grade",
    trackingLevel: "major_system",
    visibleToHomeowner: false,
    inspectorOnly: true,
    expectedLifeYears: { low: 50, median: 80, high: 100 },
    weibullShape: 2.0,
    weibullScale: 85,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.90, reason: "Expansive clay soils in Gulf Coast; moisture fluctuation causes differential settlement. Florida slab-on-grade is standard but sandy soils can erode under slab." },
      { region: "cold_harsh", adjustmentFactor: 0.85, reason: "Frost heave below footings if not at proper depth; freeze-thaw cracking" },
    ],
    replacementCost: { low: 5000, median: 15000, high: 50000 },
    dataFields: [
      { fieldName: "visible_cracks", fieldType: "select", options: ["None", "Hairline (<1/16 in)", "Minor (1/16-1/4 in)", "Major (>1/4 in)", "Structural concern"], required: true, inspectorField: true, homeownerField: false },
      { fieldName: "evidence_of_movement", fieldType: "boolean", required: true, inspectorField: true, homeownerField: false },
      { fieldName: "moisture_intrusion", fieldType: "boolean", required: false, inspectorField: true, homeownerField: false },
    ],
    maintenanceTaskIds: ["task.structural.slab.inspect_cracks", "task.structural.slab.drainage_check"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "structural.foundation.crawlspace",
    category: "structural",
    subcategory: "foundation",
    systemName: "Foundation — Crawl Space",
    trackingLevel: "major_system",
    visibleToHomeowner: false,
    inspectorOnly: true,
    expectedLifeYears: { low: 40, median: 70, high: 100 },
    weibullShape: 2.0,
    weibullScale: 75,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.80, reason: "Crawl space moisture is the #1 structural issue in Gulf Coast homes. Vapor barrier and ventilation are critical. Wood rot, termites, and mold thrive here." },
      { region: "marine", adjustmentFactor: 0.75, reason: "Coastal flooding and salt air degrade crawl space piers and joists aggressively" },
    ],
    replacementCost: { low: 3000, median: 12000, high: 40000 },
    dataFields: [
      { fieldName: "vapor_barrier", fieldType: "select", options: ["Full coverage", "Partial", "None", "Encapsulated"], required: true, inspectorField: true, homeownerField: false },
      { fieldName: "ventilation", fieldType: "select", options: ["Vented (traditional)", "Sealed/Conditioned", "Insufficient", "Unknown"], required: true, inspectorField: true, homeownerField: false },
      { fieldName: "moisture_present", fieldType: "boolean", required: true, inspectorField: true, homeownerField: false },
      { fieldName: "wood_damage", fieldType: "select", options: ["None", "Minor", "Moderate", "Severe"], required: true, inspectorField: true, homeownerField: false },
    ],
    maintenanceTaskIds: ["task.structural.crawl.inspect_moisture", "task.structural.crawl.check_vapor_barrier", "task.structural.crawl.pest_inspection"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "structural.framing",
    category: "structural",
    subcategory: "framing",
    systemName: "Structural Framing",
    trackingLevel: "component",
    visibleToHomeowner: false,
    inspectorOnly: true,
    expectedLifeYears: { low: 50, median: 80, high: 100 },
    weibullShape: 1.8,
    weibullScale: 90,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.85, reason: "Termites and wood-destroying organisms are the primary threat to framing in the Gulf Coast. Annual WDO inspection is standard in Florida." },
      { region: "marine", adjustmentFactor: 0.80, reason: "Salt air and persistent moisture accelerate fastener corrosion and wood degradation" },
    ],
    replacementCost: { low: 2000, median: 10000, high: 50000 },
    dataFields: [
      { fieldName: "material", fieldType: "select", options: ["Dimensional lumber", "Engineered (LVL/TJI)", "Steel", "Combination"], required: true, inspectorField: true, homeownerField: false },
      { fieldName: "visible_damage", fieldType: "select", options: ["None", "Minor — cosmetic", "Moderate — repairs needed", "Severe — structural concern"], required: true, inspectorField: true, homeownerField: false },
      { fieldName: "wdo_evidence", fieldType: "boolean", required: true, inspectorField: true, homeownerField: false },
    ],
    maintenanceTaskIds: ["task.structural.framing.inspect", "task.structural.framing.wdo_inspection"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "structural.insulation.attic",
    category: "structural",
    subcategory: "insulation",
    systemName: "Attic Insulation",
    trackingLevel: "component",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 20, median: 40, high: 80 },
    weibullShape: 1.8,
    weibullScale: 45,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.85, reason: "Attic temperatures in Gulf Coast homes can exceed 150°F; insulation settles and degrades faster. Moisture from bathroom vents improperly exhausted into attic is common." },
    ],
    replacementCost: { low: 1000, median: 2500, high: 6000 },
    dataFields: [
      { fieldName: "type", fieldType: "select", options: ["Fiberglass batt", "Blown fiberglass", "Blown cellulose", "Spray foam — open cell", "Spray foam — closed cell", "Radiant barrier"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "approximate_depth_inches", fieldType: "number", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Good — even coverage", "Fair — some gaps or settling", "Poor — thin, compressed, or damaged"], required: true, inspectorField: true, homeownerField: false },
    ],
    maintenanceTaskIds: ["task.structural.attic_insulation.inspect", "task.structural.attic_insulation.add_depth"],
    isActive: true,
    lastUpdated: Date.now(),
  },
];

// ============================================================
// LANDSCAPE (7 entries)
// ============================================================

export const LANDSCAPE_CATALOG: CatalogEntry[] = [
  {
    catalogId: "landscape.irrigation_system",
    category: "landscape",
    subcategory: "irrigation",
    systemName: "Irrigation/Sprinkler System",
    trackingLevel: "major_system",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 10, median: 18, high: 25 },
    weibullShape: 2.8,
    weibullScale: 19,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.90, reason: "Year-round use in Florida panhandle; UV degrades exposed heads and valves. Sandy soil shifts zones. Hard water deposits clog nozzles." },
      { region: "cold_harsh", adjustmentFactor: 0.85, reason: "Freeze damage is primary failure mode if not properly winterized. Underground pipes crack from frost." },
    ],
    replacementCost: { low: 2000, median: 4500, high: 10000 },
    dataFields: [
      { fieldName: "zones", fieldType: "number", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "controller_type", fieldType: "select", options: ["Smart (WiFi)", "Timer-based", "Manual", "Unknown"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.landscape.irrigation.seasonal_adjust", "task.landscape.irrigation.inspect_heads", "task.landscape.irrigation.winterize", "task.landscape.irrigation.backflow_test"],
    iotCompatible: true,
    iotDeviceTypes: ["smart_irrigation_controller", "soil_moisture_sensor", "rain_sensor"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "landscape.lawn",
    category: "landscape",
    subcategory: "Turf",
    systemName: "Lawn/Turf",
    trackingLevel: "cosmetic",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 999, median: 999, high: 999 },
    weibullShape: 1.0,
    weibullScale: 999,
    replacementCost: { low: 0, median: 0, high: 0 },
    dataFields: [
      { fieldName: "grass_type", fieldType: "select", options: ["St. Augustine", "Bermuda", "Zoysia", "Centipede", "Bahia", "Fescue", "Kentucky Bluegrass", "Mixed/Unknown"], required: false, inspectorField: false, homeownerField: true },
      { fieldName: "approximate_sqft", fieldType: "number", required: false, inspectorField: false, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: false, inspectorField: false, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.landscape.lawn.mow", "task.landscape.lawn.fertilize", "task.landscape.lawn.aerate", "task.landscape.lawn.pest_treatment"],
    careKitProductTypes: ["lawn_fertilizer", "weed_control"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "landscape.trees_shrubs",
    category: "landscape",
    subcategory: "Plantings",
    systemName: "Trees & Shrubs",
    trackingLevel: "cosmetic",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 999, median: 999, high: 999 },
    weibullShape: 1.0,
    weibullScale: 999,
    replacementCost: { low: 0, median: 0, high: 0 },
    dataFields: [
      { fieldName: "mature_trees_near_structure", fieldType: "boolean", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Healthy", "Fair", "Declining", "Dead/Hazardous"], required: false, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.landscape.trees.prune", "task.landscape.trees.inspect_hazard", "task.landscape.shrubs.trim"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "landscape.pool",
    category: "landscape",
    subcategory: "pool",
    systemName: "Swimming Pool",
    trackingLevel: "major_system",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 15, median: 25, high: 40 },
    weibullShape: 2.5,
    weibullScale: 28,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.90, reason: "Year-round pool use in Florida extends chemical exposure on surfaces. Algae growth is aggressive. Screen enclosures help but debris still accumulates." },
    ],
    replacementCost: { low: 10000, median: 25000, high: 60000 },
    dataFields: [
      { fieldName: "type", fieldType: "select", options: ["In-ground gunite/concrete", "In-ground fiberglass", "In-ground vinyl", "Above-ground"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "surface", fieldType: "select", options: ["Plaster", "Pebble/Aggregate", "Tile", "Fiberglass", "Vinyl liner"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.landscape.pool.balance_chemistry", "task.landscape.pool.clean", "task.landscape.pool.inspect_surface", "task.landscape.pool.resurface"],
    iotCompatible: true,
    iotDeviceTypes: ["pool_chemistry_monitor", "smart_pool_pump_controller"],
    careKitProductTypes: ["pool_test_kit", "pool_chemicals"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "landscape.pool_pump",
    category: "landscape",
    subcategory: "pool",
    systemName: "Pool Pump",
    trackingLevel: "component",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 8, median: 11, high: 15 },
    weibullShape: 3.0,
    weibullScale: 12,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.85, reason: "Year-round operation in Florida panhandle means 2x the run hours vs seasonal pools. Salt-chlorine systems add corrosion factor." },
    ],
    replacementCost: { low: 500, median: 1200, high: 3000 },
    dataFields: [
      { fieldName: "type", fieldType: "select", options: ["Single-speed", "Dual-speed", "Variable-speed"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "manufacturer", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.landscape.pool_pump.clean_basket", "task.landscape.pool_pump.inspect_seal", "task.landscape.pool_pump.lubricate"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "landscape.pool_heater",
    category: "landscape",
    subcategory: "pool",
    systemName: "Pool Heater",
    trackingLevel: "component",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 7, median: 12, high: 18 },
    weibullShape: 2.8,
    weibullScale: 13,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.90, reason: "Less heating demand in Florida but salt air and outdoor exposure degrade heat exchangers. Gas heaters corrode faster near coast." },
      { region: "marine", adjustmentFactor: 0.75, reason: "Salt air is extremely aggressive on heat exchanger copper and cabinet steel" },
    ],
    replacementCost: { low: 1500, median: 3500, high: 7000 },
    dataFields: [
      { fieldName: "type", fieldType: "select", options: ["Gas (natural)", "Gas (propane)", "Electric heat pump", "Solar"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "manufacturer", fieldType: "text", required: false, inspectorField: true, homeownerField: true },
      { fieldName: "condition", fieldType: "select", options: ["Excellent", "Good", "Fair", "Poor"], required: true, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.landscape.pool_heater.inspect", "task.landscape.pool_heater.descale", "task.landscape.pool_heater.clean"],
    isActive: true,
    lastUpdated: Date.now(),
  },
  {
    catalogId: "landscape.screen_enclosure",
    category: "landscape",
    subcategory: "enclosure",
    systemName: "Screen Enclosure (Lanai)",
    trackingLevel: "component",
    visibleToHomeowner: true,
    inspectorOnly: false,
    expectedLifeYears: { low: 10, median: 15, high: 20 },
    weibullShape: 3.0,
    weibullScale: 16,
    regionalFactors: [
      { region: "hot_humid", adjustmentFactor: 0.80, reason: "Florida panhandle screen enclosures take direct hurricane/tropical storm wind loads. UV degradation is constant. Re-screening is the most common maintenance expense for Florida pool homes." },
      { region: "marine", adjustmentFactor: 0.75, reason: "Salt air corrodes aluminum framing; screens degrade faster from salt buildup" },
    ],
    replacementCost: { low: 2000, median: 5000, high: 15000 },
    dataFields: [
      { fieldName: "frame_material", fieldType: "select", options: ["Aluminum", "Steel", "Other"], required: false, inspectorField: true, homeownerField: true },
      { fieldName: "screen_condition", fieldType: "select", options: ["Good — intact", "Fair — minor tears", "Poor — significant damage", "Needs full re-screen"], required: true, inspectorField: true, homeownerField: true },
      { fieldName: "approximate_sqft", fieldType: "number", required: false, inspectorField: true, homeownerField: true },
    ],
    maintenanceTaskIds: ["task.landscape.screen_enclosure.inspect", "task.landscape.screen_enclosure.clean", "task.landscape.screen_enclosure.patch_screen"],
    isActive: true,
    lastUpdated: Date.now(),
  },
];
