import { internalMutation } from "../_generated/server";

const hvacComponents = [
  // ============================================================
  // COOLING
  // ============================================================
  {
    key: "central_ac_split",
    systemCategory: "hvac",
    subsystem: "cooling",
    name: "Central A/C — Split System",
    description: "Split-system central air conditioning with outdoor condenser and indoor evaporator coil paired with a furnace or air handler",
    commonBrands: ["Trane", "Carrier", "Lennox", "Rheem", "Goodman", "York", "Bryant", "American Standard", "Daikin", "Amana"],
    weibull: {
      shape: 3.5,
      scale: 17.2,
      medianLifespan: 15.5,
      p10Life: 8.5,
      p90Life: 22.0,
      dataSource: "ASHRAE equipment life expectancy tables, manufacturer warranty data, ACCA service records",
      notes: "Strong wear-out pattern. Compressor failure is primary end-of-life mode. Coastal salt air and continuous run cycles in hot-humid zones are the biggest life reducers.",
    },
    costRange: {
      replacementLow: 3500,
      replacementHigh: 7500,
      replacementMedian: 5200,
      laborPercent: 45,
      year: 2025,
      notes: "Includes matched indoor coil. Variable-speed and high-SEER units at upper range. Does not include ductwork modifications.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.82, reason: "Continuous summer run cycles 8-10 months/year, high condensate load, salt air corrosion in coastal areas" },
      hotDry: { scaleMultiplier: 0.88, reason: "Extreme heat cycles and dust infiltration degrade condenser coils and electrical components" },
      coldHarsh: { scaleMultiplier: 1.08, reason: "Shorter cooling seasons reduce compressor run hours significantly" },
      coldModerate: { scaleMultiplier: 0.97, reason: "Moderate cooling demand with humid summers" },
      marine: { scaleMultiplier: 0.78, reason: "Salt air corrosion is dominant degradation factor on outdoor components" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline region with moderate seasonal use" },
    },
    efficiencyRatings: {
      metric: "SEER2",
      minimumCode: 14.3,
      goodRating: 16,
      excellentRating: 20,
      notes: "SEER2 replaced SEER Jan 2023. Northern minimum 13.4, southern minimum 14.3. ENERGY STAR requires 15+.",
    },
    fuelType: "electric",
    typicalCapacities: ["1.5 ton", "2 ton", "2.5 ton", "3 ton", "3.5 ton", "4 ton", "5 ton"],
    warrantyCoverage: {
      typicalPartsYears: 10,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Must register within 60-90 days for full 10-year parts. Unregistered drops to 5-year. Compressor often has separate 10-year warranty.",
    },
    criticality: "high" as const,
    tags: ["cooling", "comfort", "energy", "seasonal", "common"],
  },
  {
    key: "central_ac_package",
    systemCategory: "hvac",
    subsystem: "cooling",
    name: "Central A/C — Package Unit",
    description: "Self-contained package unit with all components in a single outdoor cabinet, typically roof-mounted or ground-level on a slab",
    commonBrands: ["Trane", "Carrier", "Lennox", "Rheem", "Goodman", "York"],
    weibull: {
      shape: 3.2,
      scale: 15.8,
      medianLifespan: 14.0,
      p10Life: 7.5,
      p90Life: 20.5,
      dataSource: "ASHRAE, manufacturer data, commercial/residential crossover service records",
      notes: "Slightly shorter life than split systems due to full outdoor exposure. All components subject to weather. Common in manufactured homes and slab-on-grade construction.",
    },
    costRange: {
      replacementLow: 4000,
      replacementHigh: 8500,
      replacementMedian: 5800,
      laborPercent: 40,
      year: 2025,
      notes: "Crane/lift equipment may be needed for roof-mounted units, adding $500-$1500.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.78, reason: "Full outdoor exposure accelerates degradation. Very common unit type in Gulf Coast." },
      hotDry: { scaleMultiplier: 0.85, reason: "Sand/dust infiltration and UV on all components" },
      coldHarsh: { scaleMultiplier: 1.05, reason: "Less common; shorter cooling season when present" },
      coldModerate: { scaleMultiplier: 0.95, reason: "Moderate use with full weather exposure" },
      marine: { scaleMultiplier: 0.75, reason: "Aggressive salt corrosion on entire unit" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    typicalCapacities: ["2 ton", "2.5 ton", "3 ton", "3.5 ton", "4 ton", "5 ton"],
    warrantyCoverage: {
      typicalPartsYears: 10,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Same warranty structure as split systems. Registration required.",
    },
    criticality: "high" as const,
    tags: ["cooling", "comfort", "energy", "seasonal", "manufactured_home"],
  },
  {
    key: "heat_pump_split",
    systemCategory: "hvac",
    subsystem: "cooling",
    name: "Heat Pump — Air-Source Split System",
    description: "Provides both heating and cooling via refrigerant cycle reversal. Outdoor condenser/compressor with indoor air handler and evaporator coil.",
    commonBrands: ["Trane", "Carrier", "Lennox", "Rheem", "Goodman", "Daikin", "Mitsubishi", "Bosch"],
    weibull: {
      shape: 3.2,
      scale: 16.0,
      medianLifespan: 14.5,
      p10Life: 8.0,
      p90Life: 21.0,
      dataSource: "ASHRAE, DOE heat pump field studies, manufacturer warranty claims data",
      notes: "Slightly shorter than AC-only due to year-round operation (heating + cooling). Reversing valve is an additional failure point. Cold-climate models with vapor injection are newer with less life data.",
    },
    costRange: {
      replacementLow: 4500,
      replacementHigh: 9000,
      replacementMedian: 6500,
      laborPercent: 42,
      year: 2025,
      notes: "Premium over straight AC for dual-mode capability. Variable-speed inverter models at upper range. Federal tax credits (25C) can offset $2000.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.85, reason: "Year-round operation with heavy cooling demand. Reversing valve sees constant use." },
      hotDry: { scaleMultiplier: 0.88, reason: "Heavy cooling demand plus heating in winter" },
      coldHarsh: { scaleMultiplier: 0.80, reason: "Defrost cycles, low-temperature stress on compressor, auxiliary heat strip wear. Cold-climate models improve this." },
      coldModerate: { scaleMultiplier: 0.92, reason: "Balanced year-round use, moderate stress" },
      marine: { scaleMultiplier: 0.82, reason: "Salt air corrosion, but mild temps reduce thermal stress" },
      mixed: { scaleMultiplier: 1.0, reason: "Ideal climate for heat pumps — moderate heating and cooling loads" },
    },
    efficiencyRatings: {
      metric: "SEER2 / HSPF2",
      minimumCode: 14.3,
      goodRating: 16,
      excellentRating: 20,
      notes: "Dual rating: SEER2 for cooling, HSPF2 for heating. ENERGY STAR requires SEER2 15.2+ and HSPF2 7.8+. Variable-speed inverters reach SEER2 20-24.",
    },
    fuelType: "electric",
    typicalCapacities: ["1.5 ton", "2 ton", "2.5 ton", "3 ton", "3.5 ton", "4 ton", "5 ton"],
    warrantyCoverage: {
      typicalPartsYears: 10,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Registration required. Some manufacturers offer 12-year compressor warranty on premium models.",
    },
    criticality: "high" as const,
    tags: ["cooling", "heating", "heat_pump", "electrification", "energy", "incentives"],
  },
  {
    key: "heat_pump_geothermal",
    systemCategory: "hvac",
    subsystem: "cooling",
    name: "Heat Pump — Ground-Source (Geothermal)",
    description: "Uses underground loop field to exchange heat with the earth for highly efficient heating and cooling. Indoor unit with ground loop.",
    commonBrands: ["WaterFurnace", "ClimateMaster", "Bosch", "Carrier (GreenSpeed)", "Trane", "Bryant"],
    weibull: {
      shape: 4.0,
      scale: 24.0,
      medianLifespan: 22.0,
      p10Life: 14.0,
      p90Life: 30.0,
      dataSource: "DOE geothermal studies, manufacturer data, IGSHPA field reports",
      notes: "Indoor unit lasts 20-25 years. Ground loop lasts 50+ years. Shape parameter high because failure mode is predictable compressor wear. No outdoor weather exposure.",
    },
    costRange: {
      replacementLow: 12000,
      replacementHigh: 30000,
      replacementMedian: 20000,
      laborPercent: 50,
      year: 2025,
      notes: "Includes indoor unit replacement. Ground loop typically NOT replaced (50+ year life). New installation with loop: $18K-$45K. 30% federal tax credit (25D) applies.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.95, reason: "Ground temps stable but higher, reducing cooling efficiency delta" },
      hotDry: { scaleMultiplier: 0.97, reason: "Dry soil can reduce loop efficiency without proper grouting" },
      coldHarsh: { scaleMultiplier: 1.0, reason: "Excellent performance — ground temp advantage greatest in extreme cold" },
      coldModerate: { scaleMultiplier: 1.02, reason: "Ideal conditions for geothermal" },
      marine: { scaleMultiplier: 1.0, reason: "No outdoor exposure eliminates salt air concern" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    efficiencyRatings: {
      metric: "EER / COP",
      minimumCode: 16,
      goodRating: 20,
      excellentRating: 25,
      notes: "EER for cooling, COP for heating. Geothermal COP of 3.5-5.0 means 350-500% efficiency. Best available residential HVAC technology.",
    },
    fuelType: "electric",
    typicalCapacities: ["2 ton", "3 ton", "4 ton", "5 ton", "6 ton"],
    warrantyCoverage: {
      typicalPartsYears: 10,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Ground loops often warrantied 50 years by installer. Indoor unit 10-year parts standard.",
    },
    criticality: "high" as const,
    tags: ["cooling", "heating", "geothermal", "high_efficiency", "incentives", "premium"],
  },
  {
    key: "mini_split_single",
    systemCategory: "hvac",
    subsystem: "cooling",
    name: "Ductless Mini-Split — Single Zone",
    description: "Wall-mounted indoor head unit with dedicated outdoor condenser. Provides heating and cooling for a single room or zone without ductwork.",
    commonBrands: ["Mitsubishi", "Fujitsu", "Daikin", "LG", "Samsung", "MrCool", "Senville", "Pioneer"],
    weibull: {
      shape: 3.0,
      scale: 15.5,
      medianLifespan: 14.0,
      p10Life: 7.5,
      p90Life: 20.0,
      dataSource: "Manufacturer data, Asian market longevity studies (longer deployment history), US service records",
      notes: "Well-established technology globally. Indoor head units are simple (fan + coil). Compressor in outdoor unit is primary failure point. Inverter-driven compressors have different failure profiles than fixed-speed.",
    },
    costRange: {
      replacementLow: 2000,
      replacementHigh: 5000,
      replacementMedian: 3500,
      laborPercent: 40,
      year: 2025,
      notes: "Single zone 9K-18K BTU. DIY-install brands (MrCool) at low end. Professional Mitsubishi/Daikin install at high end.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.85, reason: "Continuous operation in cooling mode. Condensate management important." },
      hotDry: { scaleMultiplier: 0.90, reason: "Heavy cooling demand but dry air reduces condensate issues" },
      coldHarsh: { scaleMultiplier: 0.82, reason: "Cold-climate models (Mitsubishi Hyper-Heat, Fujitsu XLTH) essential. Standard units lose capacity below 15°F." },
      coldModerate: { scaleMultiplier: 0.95, reason: "Moderate heating demand within normal operating range" },
      marine: { scaleMultiplier: 0.80, reason: "Salt air on outdoor unit. Otherwise mild conditions are ideal." },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    efficiencyRatings: {
      metric: "SEER2 / HSPF2",
      minimumCode: 15,
      goodRating: 20,
      excellentRating: 28,
      notes: "Mini-splits are inherently more efficient than ducted systems (no duct losses). Top models reach SEER2 30+.",
    },
    fuelType: "electric",
    typicalCapacities: ["9,000 BTU", "12,000 BTU", "15,000 BTU", "18,000 BTU", "24,000 BTU"],
    warrantyCoverage: {
      typicalPartsYears: 7,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Mitsubishi offers 12-year compressor warranty. Budget brands typically 5-year parts.",
    },
    criticality: "medium" as const,
    tags: ["cooling", "heating", "ductless", "zoning", "addition", "retrofit"],
  },
  {
    key: "mini_split_multi",
    systemCategory: "hvac",
    subsystem: "cooling",
    name: "Ductless Mini-Split — Multi-Zone",
    description: "Single outdoor condenser serving 2-5 indoor head units in different rooms. Each zone independently controlled.",
    commonBrands: ["Mitsubishi", "Fujitsu", "Daikin", "LG", "Samsung"],
    weibull: {
      shape: 2.8,
      scale: 14.5,
      medianLifespan: 13.0,
      p10Life: 7.0,
      p90Life: 19.0,
      dataSource: "Manufacturer data, HVAC contractor service records",
      notes: "Multi-zone outdoor units work harder than single-zone. More complex refrigerant distribution. Failure of outdoor unit affects all zones.",
    },
    costRange: {
      replacementLow: 5000,
      replacementHigh: 15000,
      replacementMedian: 9000,
      laborPercent: 45,
      year: 2025,
      notes: "Varies heavily by number of zones. 2-zone: $5K-$8K. 4-zone: $10K-$15K. Line set routing is biggest labor variable.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.83, reason: "Heavy year-round load across multiple zones" },
      hotDry: { scaleMultiplier: 0.88, reason: "High cooling demand on shared compressor" },
      coldHarsh: { scaleMultiplier: 0.78, reason: "Compressor works hardest in extreme cold across multiple zones" },
      coldModerate: { scaleMultiplier: 0.93, reason: "Balanced load" },
      marine: { scaleMultiplier: 0.80, reason: "Salt air corrosion on outdoor unit" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    typicalCapacities: ["24,000 BTU (2-zone)", "36,000 BTU (3-zone)", "48,000 BTU (4-zone)", "60,000 BTU (5-zone)"],
    warrantyCoverage: {
      typicalPartsYears: 10,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Same as single-zone from same manufacturer.",
    },
    criticality: "high" as const,
    tags: ["cooling", "heating", "ductless", "whole_house", "zoning"],
  },

  // ============================================================
  // HEATING
  // ============================================================
  {
    key: "gas_furnace_single",
    systemCategory: "hvac",
    subsystem: "heating",
    name: "Gas Furnace — Single Stage",
    description: "Natural gas or propane forced-air furnace with single-stage burner. Runs at full capacity or off. Most common furnace type in existing homes.",
    commonBrands: ["Trane", "Carrier", "Lennox", "Rheem", "Goodman", "York", "Bryant", "American Standard"],
    weibull: {
      shape: 3.8,
      scale: 21.0,
      medianLifespan: 19.5,
      p10Life: 11.5,
      p90Life: 27.0,
      dataSource: "ASHRAE, Gas Technology Institute studies, manufacturer warranty data, HVAC service industry surveys",
      notes: "Gas furnaces have longer lives than AC due to simpler mechanical operation. Heat exchanger cracking is primary end-of-life failure — safety critical. Inducer motor and ignitor are common interim repairs.",
    },
    costRange: {
      replacementLow: 2500,
      replacementHigh: 5500,
      replacementMedian: 3800,
      laborPercent: 45,
      year: 2025,
      notes: "Does NOT include AC coil — just furnace. Often replaced alongside AC as matched system.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 1.15, reason: "Light use — maybe 2-3 months/year. Less wear extends life significantly." },
      hotDry: { scaleMultiplier: 1.05, reason: "Short heating season in desert winters" },
      coldHarsh: { scaleMultiplier: 0.85, reason: "6-7 months of heavy use. Maximum thermal cycling and run hours." },
      coldModerate: { scaleMultiplier: 0.92, reason: "4-5 months moderate use" },
      marine: { scaleMultiplier: 1.05, reason: "Mild heating demand, gas furnace runs gently" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline — moderate heating season" },
    },
    efficiencyRatings: {
      metric: "AFUE",
      minimumCode: 80,
      goodRating: 90,
      excellentRating: 96,
      notes: "80% AFUE = standard efficiency (non-condensing). 90%+ = high efficiency (condensing, requires condensate drain). 96-98% is maximum available.",
    },
    fuelType: "natural_gas",
    typicalCapacities: ["40,000 BTU", "60,000 BTU", "80,000 BTU", "100,000 BTU", "120,000 BTU"],
    warrantyCoverage: {
      typicalPartsYears: 10,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Heat exchanger often has separate 20-year or lifetime warranty. Registration required for full coverage.",
    },
    criticality: "high" as const,
    tags: ["heating", "gas", "forced_air", "common"],
  },
  {
    key: "gas_furnace_two_stage",
    systemCategory: "hvac",
    subsystem: "heating",
    name: "Gas Furnace — Two Stage",
    description: "Two-stage burner operates at low fire (~65% capacity) most of the time, ramping to high fire only on cold days. Quieter, more even temperatures, better humidity control.",
    commonBrands: ["Trane", "Carrier", "Lennox", "Rheem", "Goodman", "York"],
    weibull: {
      shape: 3.8,
      scale: 21.5,
      medianLifespan: 20.0,
      p10Life: 12.0,
      p90Life: 27.5,
      dataSource: "ASHRAE, manufacturer data",
      notes: "Slightly longer life than single-stage due to reduced thermal cycling at low fire. Same heat exchanger failure mode at end of life.",
    },
    costRange: {
      replacementLow: 3000,
      replacementHigh: 6500,
      replacementMedian: 4500,
      laborPercent: 43,
      year: 2025,
      notes: "15-25% premium over single-stage. Best value in cold climates where long run times at low fire improve comfort and efficiency.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 1.15, reason: "Light use extends life" },
      hotDry: { scaleMultiplier: 1.05, reason: "Short heating season" },
      coldHarsh: { scaleMultiplier: 0.87, reason: "Heavy use but low-fire mode reduces stress vs single-stage" },
      coldModerate: { scaleMultiplier: 0.93, reason: "Moderate use" },
      marine: { scaleMultiplier: 1.05, reason: "Light heating demand" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    efficiencyRatings: {
      metric: "AFUE",
      minimumCode: 80,
      goodRating: 92,
      excellentRating: 96,
      notes: "Most two-stage furnaces are 90%+ AFUE (condensing). Achieves rated efficiency better than single-stage in real-world conditions.",
    },
    fuelType: "natural_gas",
    typicalCapacities: ["60,000 BTU", "80,000 BTU", "100,000 BTU", "120,000 BTU"],
    warrantyCoverage: {
      typicalPartsYears: 10,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Same structure as single-stage. Heat exchanger warranty often 20 years.",
    },
    criticality: "high" as const,
    tags: ["heating", "gas", "forced_air", "comfort", "efficient"],
  },
  {
    key: "gas_furnace_modulating",
    systemCategory: "hvac",
    subsystem: "heating",
    name: "Gas Furnace — Modulating / Variable Speed",
    description: "Continuously adjustable burner (40-100% capacity) with variable-speed blower. Premium comfort and efficiency. Maintains tight temperature control.",
    commonBrands: ["Trane (XV)", "Carrier (Infinity)", "Lennox (SLP99V)", "Rheem (Prestige)"],
    weibull: {
      shape: 3.5,
      scale: 20.0,
      medianLifespan: 18.5,
      p10Life: 10.5,
      p90Life: 26.0,
      dataSource: "Limited field data (newer technology), manufacturer projections, early service records",
      notes: "More complex control board and gas valve. Potentially shorter life than simpler furnaces due to electronic complexity, but reduced thermal cycling may offset. Insufficient long-term field data to be confident.",
    },
    costRange: {
      replacementLow: 4000,
      replacementHigh: 8000,
      replacementMedian: 5800,
      laborPercent: 40,
      year: 2025,
      notes: "Premium product. 40-60% more than single-stage. Communicating systems may require matched thermostat.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 1.10, reason: "Light use extends life" },
      hotDry: { scaleMultiplier: 1.03, reason: "Short heating season" },
      coldHarsh: { scaleMultiplier: 0.88, reason: "Heavy use but modulating operation reduces stress" },
      coldModerate: { scaleMultiplier: 0.95, reason: "Moderate use, ideal for modulating operation" },
      marine: { scaleMultiplier: 1.05, reason: "Light use" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    efficiencyRatings: {
      metric: "AFUE",
      minimumCode: 80,
      goodRating: 96,
      excellentRating: 98,
      notes: "All modulating furnaces are condensing (90%+). Top units reach 98.7% AFUE — virtually no wasted heat.",
    },
    fuelType: "natural_gas",
    typicalCapacities: ["60,000 BTU", "80,000 BTU", "100,000 BTU", "120,000 BTU"],
    warrantyCoverage: {
      typicalPartsYears: 10,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Premium warranties available. Lennox SLP99V offers lifetime heat exchanger warranty.",
    },
    criticality: "high" as const,
    tags: ["heating", "gas", "forced_air", "premium", "comfort", "variable_speed"],
  },
  {
    key: "electric_furnace",
    systemCategory: "hvac",
    subsystem: "heating",
    name: "Electric Furnace",
    description: "Forced-air furnace using electric resistance heating elements. 100% efficient at converting electricity to heat but expensive to operate due to electric rates.",
    commonBrands: ["Goodman", "Rheem", "Nordyne", "Amana", "Carrier"],
    weibull: {
      shape: 2.5,
      scale: 22.0,
      medianLifespan: 19.5,
      p10Life: 9.5,
      p90Life: 29.0,
      dataSource: "ASHRAE, manufacturer data, utility service records",
      notes: "Mechanically simple — heating elements, blower, and controls. Long lifespan. Elements are individually replaceable, extending useful life. Wide spread due to multiple failure modes (elements, sequencers, blower).",
    },
    costRange: {
      replacementLow: 1500,
      replacementHigh: 3500,
      replacementMedian: 2300,
      laborPercent: 45,
      year: 2025,
      notes: "Inexpensive equipment. Operating cost is the concern, not replacement cost. Heat pump retrofit is almost always a better investment.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 1.15, reason: "Minimal use in mild winters" },
      hotDry: { scaleMultiplier: 1.05, reason: "Short heating season" },
      coldHarsh: { scaleMultiplier: 0.85, reason: "Heavy use, high element cycling" },
      coldModerate: { scaleMultiplier: 0.95, reason: "Moderate use" },
      marine: { scaleMultiplier: 1.05, reason: "Light use" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    typicalCapacities: ["10 kW", "15 kW", "20 kW", "25 kW"],
    warrantyCoverage: {
      typicalPartsYears: 5,
      typicalLaborYears: 1,
      extendedAvailable: false,
      notes: "Shorter warranty reflects lower equipment cost. Elements are cheap to replace individually ($20-$50 per element).",
    },
    criticality: "high" as const,
    tags: ["heating", "electric", "forced_air", "budget", "upgrade_candidate"],
  },
  {
    key: "boiler_gas_hotwater",
    systemCategory: "hvac",
    subsystem: "heating",
    name: "Boiler — Gas Hot Water (Hydronic)",
    description: "Gas-fired boiler producing hot water circulated through radiators, baseboard convectors, or radiant floor tubing",
    commonBrands: ["Weil-McLain", "Burnham", "Buderus", "Navien", "Viessmann", "Triangle Tube", "Lochinvar"],
    weibull: {
      shape: 3.5,
      scale: 26.0,
      medianLifespan: 24.0,
      p10Life: 14.0,
      p90Life: 33.0,
      dataSource: "ASHRAE, boiler manufacturer data, Northeast heating contractor records",
      notes: "Cast iron boilers can last 30-40+ years. Modern condensing boilers have shorter lives (15-20 years) due to condensate acidity on heat exchangers. Different failure profiles by technology.",
    },
    costRange: {
      replacementLow: 4000,
      replacementHigh: 12000,
      replacementMedian: 7500,
      laborPercent: 50,
      year: 2025,
      notes: "Piping modifications often needed when replacing old cast iron with modern wall-hung condensing. Near-boiler piping adds $1000-$3000.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 1.10, reason: "Rare in hot climates, light use when present" },
      hotDry: { scaleMultiplier: 1.05, reason: "Uncommon, light use" },
      coldHarsh: { scaleMultiplier: 0.88, reason: "6-7 months heavy operation, maximum thermal cycling" },
      coldModerate: { scaleMultiplier: 0.93, reason: "4-5 months moderate operation" },
      marine: { scaleMultiplier: 1.0, reason: "Mild heating load, steady operation" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    efficiencyRatings: {
      metric: "AFUE",
      minimumCode: 82,
      goodRating: 90,
      excellentRating: 95,
      notes: "Non-condensing: 82-87% AFUE. Condensing: 90-98% AFUE. Condensing requires condensate neutralizer and appropriate venting (PVC instead of masonry chimney).",
    },
    fuelType: "natural_gas",
    typicalCapacities: ["75,000 BTU", "100,000 BTU", "150,000 BTU", "200,000 BTU"],
    warrantyCoverage: {
      typicalPartsYears: 10,
      typicalLaborYears: 2,
      extendedAvailable: true,
      notes: "Heat exchanger warranty often 15-25 years. Buderus/Viessmann known for long warranties.",
    },
    criticality: "high" as const,
    tags: ["heating", "gas", "hydronic", "radiator", "northeast"],
  },
  {
    key: "baseboard_electric",
    systemCategory: "hvac",
    subsystem: "heating",
    name: "Electric Baseboard Heater",
    description: "Wall-mounted electric resistance heater along the baseboard. Zoned heating — each room has independent control. No ductwork required.",
    commonBrands: ["Cadet", "Dimplex", "Marley", "Fahrenheit", "King Electric"],
    weibull: {
      shape: 2.0,
      scale: 25.0,
      medianLifespan: 21.0,
      p10Life: 8.0,
      p90Life: 35.0,
      dataSource: "Manufacturer data, property management records",
      notes: "Extremely simple — heating element, thermostat, no moving parts. Very long life. Wide spread because failure is gradual (reduced output) rather than sudden. Thermostat failure is most common issue.",
    },
    costRange: {
      replacementLow: 150,
      replacementHigh: 400,
      replacementMedian: 250,
      laborPercent: 50,
      year: 2025,
      notes: "Per unit. Electrician needed for replacement due to hardwired connection. Equipment is cheap; labor is the cost.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 1.20, reason: "Rarely used, very long life when present" },
      hotDry: { scaleMultiplier: 1.10, reason: "Light use" },
      coldHarsh: { scaleMultiplier: 0.85, reason: "Heavy use in cold climates" },
      coldModerate: { scaleMultiplier: 0.95, reason: "Moderate use" },
      marine: { scaleMultiplier: 1.0, reason: "Moderate heating in PNW" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    typicalCapacities: ["500W (4ft)", "750W (6ft)", "1000W (8ft)", "1500W (10ft)"],
    warrantyCoverage: {
      typicalPartsYears: 5,
      typicalLaborYears: 1,
      extendedAvailable: false,
      notes: "Low replacement cost makes extended warranty unnecessary.",
    },
    criticality: "medium" as const,
    tags: ["heating", "electric", "zoned", "simple", "upgrade_candidate"],
  },

  // ============================================================
  // VENTILATION
  // ============================================================
  {
    key: "bathroom_exhaust_fan",
    systemCategory: "hvac",
    subsystem: "ventilation",
    name: "Bathroom Exhaust Fan",
    description: "Ceiling-mounted fan venting moisture and odors from bathrooms through ductwork to the exterior",
    commonBrands: ["Panasonic", "Broan-NuTone", "Delta BreezSignature", "Air King", "Fantech"],
    weibull: {
      shape: 2.5,
      scale: 12.0,
      medianLifespan: 10.5,
      p10Life: 5.0,
      p90Life: 16.5,
      dataSource: "Manufacturer data, home inspection records",
      notes: "Motor bearing failure is primary end-of-life. Humidity exposure accelerates bearing wear. Noise increase is early warning of failure. Panasonic WhisperCeiling models known for longer life (DC motor).",
    },
    costRange: {
      replacementLow: 100,
      replacementHigh: 350,
      replacementMedian: 200,
      laborPercent: 50,
      year: 2025,
      notes: "Equipment $30-$150. Labor for ceiling access and duct connection is the main cost.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.80, reason: "Constant moisture exposure. Critical for mold prevention — run frequently." },
      hotDry: { scaleMultiplier: 1.10, reason: "Low moisture, infrequent use" },
      coldHarsh: { scaleMultiplier: 0.95, reason: "Cold air backdraft and condensation in duct" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard use" },
      marine: { scaleMultiplier: 0.85, reason: "High moisture environment" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    typicalCapacities: ["50 CFM", "80 CFM", "110 CFM", "150 CFM"],
    warrantyCoverage: {
      typicalPartsYears: 3,
      typicalLaborYears: 0,
      extendedAvailable: false,
      notes: "Panasonic offers 6-year warranty on WhisperCeiling line — industry leading.",
    },
    criticality: "medium" as const,
    tags: ["ventilation", "moisture", "bathroom", "mold_prevention"],
  },
  {
    key: "kitchen_range_hood",
    systemCategory: "hvac",
    subsystem: "ventilation",
    name: "Kitchen Range Hood / Exhaust",
    description: "Over-stove exhaust hood venting cooking fumes, grease, and moisture to the exterior. Ducted or recirculating.",
    commonBrands: ["Broan-NuTone", "Zephyr", "GE", "KitchenAid", "Cosmo", "Hauslane", "FOTILE"],
    weibull: {
      shape: 2.8,
      scale: 15.0,
      medianLifespan: 13.5,
      p10Life: 7.0,
      p90Life: 20.0,
      dataSource: "Manufacturer data, appliance industry reports",
      notes: "Motor and fan assembly failure is primary mode. Grease accumulation accelerates wear if filters aren't cleaned regularly. Ducted hoods last longer than recirculating due to less grease buildup on motor.",
    },
    costRange: {
      replacementLow: 200,
      replacementHigh: 1500,
      replacementMedian: 600,
      laborPercent: 40,
      year: 2025,
      notes: "Wide range from basic builder-grade to premium. Ductwork modification adds $300-$800 if needed.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.92, reason: "Humidity and grease combine to accelerate motor wear" },
      hotDry: { scaleMultiplier: 1.0, reason: "Standard conditions" },
      coldHarsh: { scaleMultiplier: 0.95, reason: "Cold air backdraft through duct can cause condensation" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 0.90, reason: "Salt air plus grease" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    typicalCapacities: ["200 CFM", "400 CFM", "600 CFM", "900 CFM", "1200 CFM"],
    warrantyCoverage: {
      typicalPartsYears: 3,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Premium brands offer 5-year parts warranties.",
    },
    criticality: "medium" as const,
    tags: ["ventilation", "kitchen", "air_quality", "grease"],
  },
  {
    key: "erv",
    systemCategory: "hvac",
    subsystem: "ventilation",
    name: "Energy Recovery Ventilator (ERV)",
    description: "Whole-house ventilation unit that exchanges stale indoor air with fresh outdoor air while recovering energy (heat and moisture) between the streams",
    commonBrands: ["Panasonic", "Broan", "Fantech", "Zehnder", "RenewAire", "Lifebreath"],
    weibull: {
      shape: 3.0,
      scale: 17.0,
      medianLifespan: 15.5,
      p10Life: 8.5,
      p90Life: 22.0,
      dataSource: "Manufacturer data, energy efficiency program monitoring",
      notes: "Core/wheel lasts 15-20+ years. Motors and controls are primary failure points. Filter maintenance is critical — neglect drastically shortens motor life.",
    },
    costRange: {
      replacementLow: 1500,
      replacementHigh: 4000,
      replacementMedian: 2500,
      laborPercent: 50,
      year: 2025,
      notes: "Includes ductwork connections. Standalone ERVs cheaper than ducted-to-HVAC integrated units.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.90, reason: "Year-round operation. ERV preferred over HRV in humid climates for moisture management." },
      hotDry: { scaleMultiplier: 0.95, reason: "Good application for maintaining indoor humidity" },
      coldHarsh: { scaleMultiplier: 0.88, reason: "Heavy winter use. Frost management important in extreme cold." },
      coldModerate: { scaleMultiplier: 0.95, reason: "Moderate use" },
      marine: { scaleMultiplier: 0.92, reason: "Important for moisture-laden PNW air" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    typicalCapacities: ["70 CFM", "100 CFM", "150 CFM", "200 CFM"],
    warrantyCoverage: {
      typicalPartsYears: 5,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Core elements often warrantied longer than motors.",
    },
    criticality: "medium" as const,
    tags: ["ventilation", "air_quality", "energy_recovery", "tight_homes"],
  },

  // ============================================================
  // CONTROLS
  // ============================================================
  {
    key: "thermostat_manual",
    systemCategory: "hvac",
    subsystem: "controls",
    name: "Thermostat — Manual / Non-Programmable",
    description: "Basic thermostat with manual temperature adjustment. No scheduling or remote access.",
    commonBrands: ["Honeywell", "White-Rodgers", "Lux"],
    weibull: {
      shape: 1.8,
      scale: 18.0,
      medianLifespan: 15.0,
      p10Life: 5.5,
      p90Life: 27.0,
      dataSource: "Manufacturer data, HVAC service records",
      notes: "Very simple device. Mercury switch models last decades. Digital models have shorter lives due to electronics. Wide spread reflects random electronic failures.",
    },
    costRange: {
      replacementLow: 50,
      replacementHigh: 150,
      replacementMedian: 80,
      laborPercent: 50,
      year: 2025,
      notes: "Equipment is $15-$40. Labor for wiring is the main cost. Many homeowners DIY.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 1.0, reason: "Standard conditions" },
      hotDry: { scaleMultiplier: 1.0, reason: "Standard conditions" },
      coldHarsh: { scaleMultiplier: 1.0, reason: "Standard conditions" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard conditions" },
      marine: { scaleMultiplier: 1.0, reason: "Standard conditions" },
      mixed: { scaleMultiplier: 1.0, reason: "Indoor device — region has minimal impact" },
    },
    fuelType: "electric",
    typicalCapacities: ["24V low voltage"],
    warrantyCoverage: {
      typicalPartsYears: 5,
      typicalLaborYears: 0,
      extendedAvailable: false,
      notes: "Low cost makes replacement preferable to warranty claims.",
    },
    criticality: "medium" as const,
    tags: ["controls", "thermostat", "basic", "upgrade_candidate"],
  },
  {
    key: "thermostat_smart",
    systemCategory: "hvac",
    subsystem: "controls",
    name: "Thermostat — Smart / WiFi",
    description: "WiFi-connected thermostat with scheduling, remote access, learning algorithms, and energy reporting. Integrates with smart home platforms.",
    commonBrands: ["Google Nest", "ecobee", "Honeywell Home (T-series)", "Emerson Sensi", "Carrier Cor"],
    weibull: {
      shape: 1.5,
      scale: 10.0,
      medianLifespan: 8.0,
      p10Life: 3.0,
      p90Life: 15.5,
      dataSource: "Consumer electronics reliability data, smart home industry reports",
      notes: "Consumer electronics failure profile — higher early failure rate than mechanical devices. Software obsolescence is a factor (cloud service discontinuation, security updates). Hardware typically outlasts software support.",
    },
    costRange: {
      replacementLow: 120,
      replacementHigh: 350,
      replacementMedian: 220,
      laborPercent: 30,
      year: 2025,
      notes: "Many homeowners self-install. Pro install recommended for heat pump or multi-stage systems requiring C-wire.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 1.0, reason: "Indoor device" },
      hotDry: { scaleMultiplier: 1.0, reason: "Indoor device" },
      coldHarsh: { scaleMultiplier: 1.0, reason: "Indoor device" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Indoor device" },
      marine: { scaleMultiplier: 1.0, reason: "Indoor device" },
      mixed: { scaleMultiplier: 1.0, reason: "Indoor device — region has minimal impact" },
    },
    fuelType: "electric",
    typicalCapacities: ["24V low voltage", "C-wire recommended"],
    warrantyCoverage: {
      typicalPartsYears: 2,
      typicalLaborYears: 0,
      extendedAvailable: false,
      notes: "Consumer electronics warranty. Nest 2-year, ecobee 3-year.",
    },
    criticality: "medium" as const,
    tags: ["controls", "thermostat", "smart_home", "energy_savings", "wifi"],
  },

  // ============================================================
  // DUCTWORK & AIR DISTRIBUTION
  // ============================================================
  {
    key: "ductwork_metal",
    systemCategory: "hvac",
    subsystem: "ductwork",
    name: "Ductwork — Sheet Metal",
    description: "Rigid galvanized steel or aluminum duct system for air distribution. Trunk-and-branch or radial layout.",
    commonBrands: ["Custom fabricated", "Thermaflex", "Hart & Cooley"],
    weibull: {
      shape: 4.5,
      scale: 45.0,
      medianLifespan: 42.0,
      p10Life: 28.0,
      p90Life: 55.0,
      dataSource: "ASHRAE, building science studies, home inspection industry data",
      notes: "Metal ductwork itself lasts 40-70+ years. Joints and seals degrade first. Insulation wrap deteriorates in 15-25 years. 'Replacement' usually means sealing and re-insulating, not replacing the metal.",
    },
    costRange: {
      replacementLow: 3000,
      replacementHigh: 12000,
      replacementMedian: 7000,
      laborPercent: 65,
      year: 2025,
      notes: "Full duct replacement is rare. Sealing and insulation: $1500-$3500. Per-run replacement: $500-$1500. Full system only during major renovation.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.85, reason: "Condensation on cold duct surfaces in humid air causes corrosion and insulation damage. Duct sweating is common." },
      hotDry: { scaleMultiplier: 1.05, reason: "Dry conditions preserve ductwork. Dust accumulation is the main concern." },
      coldHarsh: { scaleMultiplier: 0.95, reason: "Temperature extremes in unconditioned spaces stress joints" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard conditions" },
      marine: { scaleMultiplier: 0.90, reason: "Moisture and mild salt air in crawlspaces" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "medium" as const,
    tags: ["ductwork", "air_distribution", "long_life", "sealing"],
  },
  {
    key: "ductwork_flex",
    systemCategory: "hvac",
    subsystem: "ductwork",
    name: "Ductwork — Flexible (Flex Duct)",
    description: "Flexible insulated duct made of wire helix wrapped in plastic liner and fiberglass insulation with outer vapor barrier. Common for branch runs.",
    commonBrands: ["Thermaflex", "Atco Rubber", "Hart & Cooley", "Johns Manville"],
    weibull: {
      shape: 3.5,
      scale: 18.0,
      medianLifespan: 16.5,
      p10Life: 9.0,
      p90Life: 23.5,
      dataSource: "ASHRAE, building science research, home inspection data",
      notes: "Outer jacket and insulation degrade before the inner liner. UV exposure in attics accelerates degradation. Sagging and kinking reduce airflow over time. Animal damage common in crawlspaces. Shorter life than metal duct.",
    },
    costRange: {
      replacementLow: 1500,
      replacementHigh: 5000,
      replacementMedian: 3000,
      laborPercent: 60,
      year: 2025,
      notes: "Material is inexpensive. Labor for attic/crawlspace access drives cost. Per-run: $200-$600.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.78, reason: "Condensation, high attic temps (150°F+), and moisture degrade outer jacket rapidly. Very common duct type in Gulf Coast." },
      hotDry: { scaleMultiplier: 0.85, reason: "Extreme attic heat deteriorates insulation and vapor barrier" },
      coldHarsh: { scaleMultiplier: 0.95, reason: "Cold attics stress jacket material" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard conditions" },
      marine: { scaleMultiplier: 0.90, reason: "Crawlspace moisture" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "medium" as const,
    tags: ["ductwork", "air_distribution", "common", "attic", "crawlspace"],
  },
  {
    key: "condensate_pump",
    systemCategory: "hvac",
    subsystem: "ductwork",
    name: "Condensate Pump",
    description: "Small pump that removes condensation from HVAC systems when gravity drainage isn't possible. Collects in reservoir and pumps to drain or exterior.",
    commonBrands: ["Little Giant", "Diversitech", "Supco", "Hartell", "Beckett"],
    weibull: {
      shape: 2.5,
      scale: 7.0,
      medianLifespan: 6.0,
      p10Life: 2.5,
      p90Life: 10.0,
      dataSource: "Manufacturer data, HVAC service records",
      notes: "High failure rate due to continuous exposure to standing water. Float switch and pump motor are common failure points. Algae growth can clog lines and jam float. Critical in humid climates where condensate volume is high.",
    },
    costRange: {
      replacementLow: 100,
      replacementHigh: 300,
      replacementMedian: 175,
      laborPercent: 45,
      year: 2025,
      notes: "Equipment $30-$80. Simple swap if accessible. Often in tight spaces requiring HVAC tech.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.70, reason: "Extremely high condensate volume. Runs constantly during 8+ month cooling season. Number one HVAC service call in Gulf Coast." },
      hotDry: { scaleMultiplier: 1.10, reason: "Low condensate volume" },
      coldHarsh: { scaleMultiplier: 1.05, reason: "Low cooling-season condensate" },
      coldModerate: { scaleMultiplier: 0.90, reason: "Moderate condensate" },
      marine: { scaleMultiplier: 0.85, reason: "Moderate moisture" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    typicalCapacities: ["65 GPH", "100 GPH"],
    warrantyCoverage: {
      typicalPartsYears: 1,
      typicalLaborYears: 0,
      extendedAvailable: false,
      notes: "Considered a consumable part. Replace proactively every 3-5 years in hot-humid climates to prevent water damage.",
    },
    criticality: "high" as const,
    tags: ["condensate", "water_damage_prevention", "common_failure", "humidity"],
  },
  {
    key: "air_handler",
    systemCategory: "hvac",
    subsystem: "ductwork",
    name: "Air Handler",
    description: "Indoor unit containing blower, evaporator coil, filter rack, and optional electric heat strips. Pairs with heat pump or AC condenser.",
    commonBrands: ["Trane", "Carrier", "Lennox", "Rheem", "Goodman", "American Standard"],
    weibull: {
      shape: 3.2,
      scale: 18.0,
      medianLifespan: 16.5,
      p10Life: 9.0,
      p90Life: 23.5,
      dataSource: "ASHRAE, manufacturer data, HVAC contractor records",
      notes: "Blower motor is primary failure point. Evaporator coil can develop refrigerant leaks. Drain pan corrosion causes water damage if pan rusts through. Typically replaced alongside outdoor unit for matched efficiency.",
    },
    costRange: {
      replacementLow: 2000,
      replacementHigh: 5000,
      replacementMedian: 3200,
      laborPercent: 45,
      year: 2025,
      notes: "Usually replaced as part of a system. Standalone replacement less common but necessary when indoor unit fails first.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.82, reason: "Constant condensate exposure, drain pan corrosion, coil stress from continuous cooling" },
      hotDry: { scaleMultiplier: 0.92, reason: "Heavy cooling use but less moisture stress" },
      coldHarsh: { scaleMultiplier: 1.02, reason: "Less cooling demand, electric heat strips add some wear" },
      coldModerate: { scaleMultiplier: 0.97, reason: "Balanced use" },
      marine: { scaleMultiplier: 0.88, reason: "Moisture concerns in crawlspace installations" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    typicalCapacities: ["2 ton", "2.5 ton", "3 ton", "3.5 ton", "4 ton", "5 ton"],
    warrantyCoverage: {
      typicalPartsYears: 10,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Matched system warranty. Must be paired with same-brand outdoor unit for full warranty coverage.",
    },
    criticality: "high" as const,
    tags: ["air_distribution", "blower", "coil", "common"],
  },

  // ============================================================
  // AIR QUALITY
  // ============================================================
  {
    key: "whole_house_dehumidifier",
    systemCategory: "hvac",
    subsystem: "air_quality",
    name: "Whole-House Dehumidifier",
    description: "Ducted dehumidification unit that works alongside HVAC to control indoor humidity independently of cooling. Critical in hot-humid climates.",
    commonBrands: ["AprilAire", "Santa Fe", "Ultra-Aire", "Honeywell"],
    weibull: {
      shape: 3.0,
      scale: 11.0,
      medianLifespan: 10.0,
      p10Life: 5.5,
      p90Life: 14.5,
      dataSource: "Manufacturer data, humidity control specialist records",
      notes: "Compressor-based dehumidification. Compressor and fan motor are primary failure points. Continuous operation in humid climates reduces life. Coil freeze-up from dirty filters is common premature failure cause.",
    },
    costRange: {
      replacementLow: 1500,
      replacementHigh: 3500,
      replacementMedian: 2200,
      laborPercent: 40,
      year: 2025,
      notes: "Equipment $800-$2000. Ducting integration adds $500-$1500. Essential equipment in Gulf Coast.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.75, reason: "Runs almost continuously 8-10 months/year. Maximum compressor hours. Essential equipment." },
      hotDry: { scaleMultiplier: 1.30, reason: "Rarely needed — dry climate" },
      coldHarsh: { scaleMultiplier: 1.15, reason: "Only needed in summer, low annual hours" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Summer use" },
      marine: { scaleMultiplier: 0.85, reason: "Year-round moisture management in PNW" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline — summer use" },
    },
    fuelType: "electric",
    typicalCapacities: ["70 pints/day", "90 pints/day", "120 pints/day", "150 pints/day"],
    warrantyCoverage: {
      typicalPartsYears: 5,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Santa Fe and AprilAire offer industry-leading warranties for this category.",
    },
    criticality: "high" as const,
    tags: ["air_quality", "humidity", "mold_prevention", "gulf_coast_essential"],
  },
  {
    key: "uv_air_purifier",
    systemCategory: "hvac",
    subsystem: "air_quality",
    name: "UV-C Air Purifier (In-Duct)",
    description: "Ultraviolet germicidal irradiation lamp installed in ductwork or near evaporator coil. Kills mold, bacteria, and viruses in the air stream.",
    commonBrands: ["RGF (REME HALO)", "Field Controls", "Honeywell UV", "Lennox PureAir", "Fresh-Aire UV"],
    weibull: {
      shape: 4.0,
      scale: 3.5,
      medianLifespan: 3.2,
      p10Life: 2.0,
      p90Life: 4.5,
      dataSource: "Manufacturer UV output decay curves",
      notes: "UV-C lamps lose germicidal effectiveness over time even while still producing visible light. Must be replaced on schedule regardless of visible operation. Housing/ballast lasts 10+ years — this is BULB life only.",
    },
    costRange: {
      replacementLow: 50,
      replacementHigh: 200,
      replacementMedian: 100,
      laborPercent: 25,
      year: 2025,
      notes: "Bulb replacement cost. Initial system installation: $500-$1500. Annual bulb replacement is the recurring cost.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.90, reason: "Continuous operation reduces bulb life slightly. Highly recommended for mold prevention on coils." },
      hotDry: { scaleMultiplier: 1.0, reason: "Standard use" },
      coldHarsh: { scaleMultiplier: 1.05, reason: "Less continuous operation" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 0.92, reason: "Important for moisture-related air quality" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    warrantyCoverage: {
      typicalPartsYears: 2,
      typicalLaborYears: 0,
      extendedAvailable: false,
      notes: "Bulb is a consumable. Replace annually or per manufacturer schedule regardless of apparent function.",
    },
    criticality: "low" as const,
    tags: ["air_quality", "uv", "mold_prevention", "consumable"],
  },
];

export const seed = internalMutation({
  handler: async (ctx) => {
    let count = 0;
    for (const comp of hvacComponents) {
      const existing = await ctx.db
        .query("componentTemplates")
        .withIndex("by_key", (q) => q.eq("key", comp.key))
        .first();
      if (!existing) {
        await ctx.db.insert("componentTemplates", comp);
        count++;
      }
    }
    console.log(`Seeded ${count} HVAC component templates`);
  },
});
