import { internalMutation } from "../_generated/server";

const components = [
  // ============================================================
  // ELECTRICAL
  // ============================================================
  {
    key: "electrical_panel_main",
    systemCategory: "electrical",
    subsystem: "service_panel",
    name: "Main Electrical Panel (Breaker Box)",
    description: "Main service panel distributing power throughout the home via circuit breakers. Typically 100A, 150A, or 200A service.",
    commonBrands: ["Square D (Schneider)", "Eaton (Cutler-Hammer)", "Siemens", "GE", "Leviton"],
    weibull: {
      shape: 3.0,
      scale: 35.0,
      medianLifespan: 32.0,
      p10Life: 17.0,
      p90Life: 45.0,
      dataSource: "NFPA data, electrical contractor records, home inspection reports",
      notes: "Panel enclosure lasts 40-60 years. Individual breakers fail first. Certain brands have known defects: Federal Pacific Stab-Lok (fire hazard, replace immediately), Zinsco/Sylvania (overheating, replace), Pushmatic (obsolete, replace). Panel upgrade from 100A to 200A is increasingly common for EV charging and electrification.",
    },
    costRange: {
      replacementLow: 1500,
      replacementHigh: 4000,
      replacementMedian: 2500,
      laborPercent: 65,
      year: 2025,
      notes: "200A panel upgrade including new breakers, weatherhead, and meter base: $2500-$4000. 400A for full electrification: $5000-$8000. Permit required.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.90, reason: "Humidity and condensation inside panel. Outdoor panels common in Gulf Coast — more weather exposure." },
      hotDry: { scaleMultiplier: 1.0, reason: "Dry conditions are gentle on electrical" },
      coldHarsh: { scaleMultiplier: 0.95, reason: "Temperature cycling, condensation in seasonal transitions" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 0.85, reason: "Salt air corrosion on connections and bus bars" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "critical" as const,
    tags: ["electrical", "panel", "safety", "capacity", "electrification"],
  },
  {
    key: "whole_house_surge_protector",
    systemCategory: "electrical",
    subsystem: "surge_protection",
    name: "Whole-House Surge Protector",
    description: "Panel-mounted surge protection device (SPD Type 2) that diverts voltage spikes from lightning, utility switching, and grid events away from home wiring.",
    commonBrands: ["Eaton", "Siemens", "Leviton", "Square D", "Intermatic"],
    weibull: {
      shape: 2.0,
      scale: 8.0,
      medianLifespan: 6.5,
      p10Life: 2.5,
      p90Life: 12.0,
      dataSource: "Manufacturer data, UL testing reports, electrical contractor records",
      notes: "SPDs degrade with each surge event. Life depends on surge frequency and severity. Lightning-prone areas (Gulf Coast, Florida) consume SPDs faster. LED indicator shows remaining protection. Replace when indicator shows depleted. Best $200 insurance policy for a house full of electronics.",
    },
    costRange: {
      replacementLow: 150,
      replacementHigh: 400,
      replacementMedian: 250,
      laborPercent: 50,
      year: 2025,
      notes: "Device $50-$150. Electrician install to panel: $100-$250. Worth it in every home, essential in lightning-prone areas.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.65, reason: "GULF COAST ESSENTIAL. 80+ thunderstorm days/year in NW Florida. Lightning is the #1 cause of HVAC compressor failure and electronics damage." },
      hotDry: { scaleMultiplier: 0.80, reason: "Monsoon lightning in desert Southwest" },
      coldHarsh: { scaleMultiplier: 1.05, reason: "Fewer thunderstorms, longer life" },
      coldModerate: { scaleMultiplier: 0.95, reason: "Moderate storm activity" },
      marine: { scaleMultiplier: 1.0, reason: "Low lightning frequency in PNW" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    criticality: "high" as const,
    tags: ["electrical", "surge", "protection", "lightning", "electronics"],
  },
  {
    key: "standby_generator",
    systemCategory: "electrical",
    subsystem: "backup_power",
    name: "Standby Generator (Whole-House)",
    description: "Permanently installed automatic generator that powers the home during utility outages. Runs on natural gas or propane. Auto-start within 10-30 seconds of outage.",
    commonBrands: ["Generac", "Kohler", "Briggs & Stratton", "Cummins", "Champion"],
    weibull: {
      shape: 3.0,
      scale: 17.0,
      medianLifespan: 15.0,
      p10Life: 8.0,
      p90Life: 22.5,
      dataSource: "Manufacturer data, generator service company records",
      notes: "Life measured in run hours more than years. 10,000-30,000 hour engine life depending on brand and maintenance. Weekly exercise cycles keep engine healthy. Battery failure is most common service call. Annual professional maintenance is critical.",
    },
    costRange: {
      replacementLow: 8000,
      replacementHigh: 25000,
      replacementMedian: 14000,
      laborPercent: 40,
      year: 2025,
      notes: "22kW whole-house: $12K-$18K installed. 48kW for large homes: $20K-$30K. Includes concrete pad, transfer switch, and gas line connection.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.85, reason: "Hurricane outages = extended run hours. Salt air corrosion on outdoor unit. Essential equipment in Gulf Coast." },
      hotDry: { scaleMultiplier: 1.0, reason: "Infrequent use" },
      coldHarsh: { scaleMultiplier: 0.90, reason: "Cold-start stress, extended winter storm outages" },
      coldModerate: { scaleMultiplier: 0.95, reason: "Moderate use" },
      marine: { scaleMultiplier: 0.88, reason: "Wind storm outages, salt air" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "natural_gas",
    typicalCapacities: ["10 kW", "16 kW", "22 kW", "38 kW", "48 kW"],
    warrantyCoverage: {
      typicalPartsYears: 5,
      typicalLaborYears: 2,
      extendedAvailable: true,
      notes: "Generac offers 5-year limited, 10-year extended. Annual maintenance required to maintain warranty.",
    },
    criticality: "medium" as const,
    tags: ["electrical", "backup_power", "hurricane", "comfort", "medical"],
  },
  {
    key: "gfci_outlet",
    systemCategory: "electrical",
    subsystem: "outlets_switches",
    name: "GFCI Outlet",
    description: "Ground-fault circuit interrupter outlet that shuts off power within milliseconds if it detects current leakage (shock hazard). Required in wet locations.",
    commonBrands: ["Leviton", "Hubbell", "Eaton", "Legrand", "Lutron"],
    weibull: {
      shape: 2.5,
      scale: 13.0,
      medianLifespan: 11.5,
      p10Life: 5.0,
      p90Life: 18.5,
      dataSource: "UL testing data, electrical contractor records, CPSC reports",
      notes: "GFCIs have a finite life — the internal sensor degrades over time. Monthly test button press is critical (and code-required). A GFCI that doesn't trip when tested MUST be replaced immediately. 2015+ models have self-test and end-of-life lockout features. Older models silently fail.",
    },
    costRange: {
      replacementLow: 50,
      replacementHigh: 150,
      replacementMedian: 85,
      laborPercent: 55,
      year: 2025,
      notes: "Device $15-$25. Electrician: $50-$100 per outlet. Protecting downstream outlets with one GFCI reduces total needed.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.85, reason: "Moisture exposure in outdoor and bathroom locations accelerates degradation" },
      hotDry: { scaleMultiplier: 1.0, reason: "Dry conditions are favorable" },
      coldHarsh: { scaleMultiplier: 0.95, reason: "Standard conditions" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 0.82, reason: "Salt air and moisture" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    criticality: "critical" as const,
    tags: ["electrical", "safety", "code_required", "monthly_test"],
  },

  // ============================================================
  // ROOFING
  // ============================================================
  {
    key: "roof_asphalt_shingle",
    systemCategory: "roofing",
    subsystem: "covering",
    name: "Asphalt Shingle Roof — Architectural (Dimensional)",
    description: "Architectural (dimensional/laminated) asphalt shingles. The standard roofing material in US residential construction. Rated 25-50 year manufacturer warranty.",
    commonBrands: ["GAF (Timberline)", "Owens Corning (Duration)", "CertainTeed (Landmark)", "Atlas", "IKO", "Tamko"],
    weibull: {
      shape: 4.5,
      scale: 23.0,
      medianLifespan: 21.5,
      p10Life: 14.5,
      p90Life: 28.5,
      dataSource: "NRCA field studies, roofing contractor data, insurance claim data, manufacturer performance tracking",
      notes: "Actual life is typically 40-60% of manufacturer warranty period. A '30-year shingle' lasts 18-22 years in most conditions. UV, thermal cycling, and wind are the primary degradation factors. Granule loss is the visible sign of aging. Attic ventilation significantly impacts life — poorly ventilated attics cook shingles from below.",
    },
    costRange: {
      replacementLow: 8000,
      replacementHigh: 18000,
      replacementMedian: 12000,
      laborPercent: 60,
      year: 2025,
      notes: "Per 2000 sq ft roof. Includes tear-off of one layer, underlayment, flashing, vents, cleanup. Additional layers add $1000-$2000 for extra tear-off.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.78, reason: "EXTREME UV exposure, 150°F+ attic temps, algae growth, hurricane wind damage. Gulf Coast roofs have the shortest shingle life in the country." },
      hotDry: { scaleMultiplier: 0.82, reason: "Extreme UV and thermal cycling. Desert sun is brutal on asphalt." },
      coldHarsh: { scaleMultiplier: 0.85, reason: "Ice dams, freeze-thaw, heavy snow load. Ice dam damage is preventable with proper insulation and ventilation." },
      coldModerate: { scaleMultiplier: 0.95, reason: "Four full seasons of cycling" },
      marine: { scaleMultiplier: 0.90, reason: "Moss/algae growth, wind-driven rain, less UV than southern climates" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "critical" as const,
    tags: ["roofing", "shingles", "common", "insurance", "curb_appeal"],
  },
  {
    key: "roof_metal_standing_seam",
    systemCategory: "roofing",
    subsystem: "covering",
    name: "Metal Roof — Standing Seam",
    description: "Premium metal roofing with raised seams and concealed fasteners. Aluminum, steel (galvalume), or copper. 40-70 year life.",
    commonBrands: ["Fabral", "Classic Metal", "McElroy", "Drexel", "Berridge", "ATAS"],
    weibull: {
      shape: 5.0,
      scale: 52.0,
      medianLifespan: 49.0,
      p10Life: 36.0,
      p90Life: 62.0,
      dataSource: "Metal Roofing Alliance, manufacturer data, commercial roofing performance data (longer track record)",
      notes: "Exceptional longevity. Concealed fastener design eliminates the most common metal roof failure point (exposed fastener rubber washers). Kynar/PVDF finish lasts 30-40 years before needing recoat. Wind resistance excellent (140+ mph rated). Best roof choice for hurricane and fire zones.",
    },
    costRange: {
      replacementLow: 15000,
      replacementHigh: 35000,
      replacementMedian: 22000,
      laborPercent: 55,
      year: 2025,
      notes: "Per 2000 sq ft roof. 2-3x asphalt shingle cost. ROI through longevity — one metal roof outlasts two shingle roofs. Insurance discounts in wind zones.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.90, reason: "Best roof choice for Gulf Coast. Wind resistant, reflects heat, no algae. Salt air can affect steel (galvalume) — aluminum preferred coastal." },
      hotDry: { scaleMultiplier: 0.95, reason: "Excellent heat reflection. Thermal expansion at seams is the only concern." },
      coldHarsh: { scaleMultiplier: 1.0, reason: "Excellent snow shedding. No ice dam risk. Ideal for cold climates." },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 0.85, reason: "Salt air on steel roofs. Use aluminum for coastal marine environments." },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "critical" as const,
    tags: ["roofing", "metal", "premium", "hurricane", "fire_resistant", "long_life"],
  },
  {
    key: "gutters_aluminum",
    systemCategory: "roofing",
    subsystem: "gutters_downspouts",
    name: "Gutters — Aluminum (Seamless)",
    description: "Seamless aluminum gutters formed on-site. Standard 5\" K-style or 6\" half-round. Directs roof water away from foundation.",
    commonBrands: ["Custom formed on-site", "Spectra Metals", "Amerimax"],
    weibull: {
      shape: 3.5,
      scale: 22.0,
      medianLifespan: 20.0,
      p10Life: 11.5,
      p90Life: 28.5,
      dataSource: "Gutter contractor data, home inspection records",
      notes: "Aluminum doesn't rust but can corrode, especially at joints and end caps. Fascia rot behind gutters from overflow is the real cost of gutter failure. Gutter guards/covers extend maintenance intervals but don't eliminate cleaning. Proper slope (1/4\" per 10 feet) is critical.",
    },
    costRange: {
      replacementLow: 1000,
      replacementHigh: 3500,
      replacementMedian: 2000,
      laborPercent: 60,
      year: 2025,
      notes: "Per typical home (150-200 linear feet). Includes downspouts and hangers. Gutter guards add $1500-$4000.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.85, reason: "Heavy rainfall, pine needles, algae growth. Gutters work overtime in Gulf Coast. Cleaning needed 3-4x/year." },
      hotDry: { scaleMultiplier: 1.10, reason: "Minimal rainfall, light duty" },
      coldHarsh: { scaleMultiplier: 0.80, reason: "Ice dams, icicle weight, freeze-thaw expansion at joints. Snow guard interaction." },
      coldModerate: { scaleMultiplier: 0.95, reason: "Leaf load, moderate rainfall" },
      marine: { scaleMultiplier: 0.88, reason: "Heavy rainfall, moss/debris, salt air" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "high" as const,
    tags: ["roofing", "gutters", "water_management", "foundation_protection", "cleaning"],
  },

  // ============================================================
  // APPLIANCES
  // ============================================================
  {
    key: "refrigerator",
    systemCategory: "appliances",
    subsystem: "kitchen",
    name: "Refrigerator",
    description: "Kitchen refrigerator/freezer. French door, side-by-side, top-freezer, or bottom-freezer configuration.",
    commonBrands: ["LG", "Samsung", "Whirlpool", "GE", "KitchenAid", "Maytag", "Frigidaire", "Bosch"],
    weibull: {
      shape: 3.5,
      scale: 15.0,
      medianLifespan: 13.5,
      p10Life: 7.5,
      p90Life: 19.5,
      dataSource: "Consumer Reports reliability data, manufacturer warranty claims, appliance service industry surveys",
      notes: "Compressor is the primary end-of-life component. Sealed system repairs ($800-$1500) are often uneconomical on older units. Smart/connected features add failure points. Ice makers and water dispensers are the most common repair needs. Simple top-freezer models last longest; French door smart models have more issues.",
    },
    costRange: {
      replacementLow: 800,
      replacementHigh: 3500,
      replacementMedian: 1800,
      laborPercent: 10,
      year: 2025,
      notes: "Delivery and installation typically included. Old unit hauling $50-$100. Built-in/panel-ready models: $4000-$12000+.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.92, reason: "Compressor works harder in warm kitchens. Garage refrigerators in unconditioned spaces have significantly shorter life." },
      hotDry: { scaleMultiplier: 0.95, reason: "Warm ambient temps increase compressor load" },
      coldHarsh: { scaleMultiplier: 1.0, reason: "Standard kitchen conditions" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 1.0, reason: "Indoor appliance" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    typicalCapacities: ["18 cu ft", "22 cu ft", "25 cu ft", "28 cu ft", "30 cu ft"],
    warrantyCoverage: {
      typicalPartsYears: 1,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Compressor typically has separate 5-10 year warranty (parts only). LG offers 10-year compressor warranty.",
    },
    criticality: "high" as const,
    tags: ["appliances", "kitchen", "daily_use", "energy"],
  },
  {
    key: "dishwasher",
    systemCategory: "appliances",
    subsystem: "kitchen",
    name: "Dishwasher",
    description: "Built-in or portable dishwasher. Standard 24\" width. Stainless steel or plastic tub interior.",
    commonBrands: ["Bosch", "KitchenAid", "Whirlpool", "GE", "LG", "Samsung", "Maytag", "Miele"],
    weibull: {
      shape: 3.0,
      scale: 11.0,
      medianLifespan: 10.0,
      p10Life: 5.5,
      p90Life: 14.5,
      dataSource: "Consumer Reports, manufacturer data, appliance service records",
      notes: "Pump and motor assembly is the primary failure. Control board failures increasing in smart/connected models. Stainless steel tubs last longer than plastic. Bosch and Miele consistently rated most reliable. Samsung and LG have more repair issues.",
    },
    costRange: {
      replacementLow: 400,
      replacementHigh: 1500,
      replacementMedian: 800,
      laborPercent: 20,
      year: 2025,
      notes: "Installation includes water line and drain connection. Old unit removal typically included.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.95, reason: "Humidity can affect electronics" },
      hotDry: { scaleMultiplier: 0.88, reason: "Hard water deposits on pump, spray arms, and heating element" },
      coldHarsh: { scaleMultiplier: 1.0, reason: "Indoor appliance" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 1.0, reason: "Indoor appliance" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    warrantyCoverage: {
      typicalPartsYears: 1,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Bosch offers 1-year full + additional rack warranty. Miele offers 2-year full.",
    },
    criticality: "medium" as const,
    tags: ["appliances", "kitchen", "daily_use"],
  },
  {
    key: "washer",
    systemCategory: "appliances",
    subsystem: "laundry",
    name: "Washing Machine",
    description: "Front-load or top-load clothes washer. Standard or high-efficiency (HE).",
    commonBrands: ["LG", "Samsung", "Whirlpool", "Maytag", "GE", "Speed Queen", "Electrolux"],
    weibull: {
      shape: 3.0,
      scale: 12.0,
      medianLifespan: 11.0,
      p10Life: 6.0,
      p90Life: 16.0,
      dataSource: "Consumer Reports, manufacturer data, appliance service industry",
      notes: "Front-loaders: more efficient but more repair-prone (door seal mold, bearing failure). Speed Queen top-loaders: commercial-grade reliability, 25-year warranty available. Smart features add failure points. Bearing and spider assembly failure is the most expensive repair ($400-$800) and often uneconomical.",
    },
    costRange: {
      replacementLow: 500,
      replacementHigh: 1500,
      replacementMedian: 900,
      laborPercent: 10,
      year: 2025,
      notes: "Delivery usually included. Stacking kit $30-$50 if stacking with dryer. Speed Queen: $1000-$1600.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.90, reason: "Front-loaders especially prone to door gasket mold in humid climates. Must leave door open between cycles." },
      hotDry: { scaleMultiplier: 0.92, reason: "Hard water deposits on pump and valves" },
      coldHarsh: { scaleMultiplier: 1.0, reason: "Indoor appliance" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 0.95, reason: "Moisture in laundry areas" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    warrantyCoverage: {
      typicalPartsYears: 1,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Speed Queen: 3-year full (residential), 5-year on select models, 25-year on some. Industry-leading.",
    },
    criticality: "medium" as const,
    tags: ["appliances", "laundry", "daily_use"],
  },
  {
    key: "dryer_electric",
    systemCategory: "appliances",
    subsystem: "laundry",
    name: "Clothes Dryer — Electric",
    description: "Electric clothes dryer with 240V heating element and tumble drum. Standard 27\" width.",
    commonBrands: ["LG", "Samsung", "Whirlpool", "Maytag", "GE", "Speed Queen", "Electrolux"],
    weibull: {
      shape: 3.0,
      scale: 14.0,
      medianLifespan: 12.5,
      p10Life: 6.5,
      p90Life: 18.5,
      dataSource: "Consumer Reports, manufacturer data, appliance service records",
      notes: "Simpler than washers — heating element, motor, drum rollers. Heating element replacement ($100-$200 repair) is common and extends life. DRYER VENT CLEANING IS CRITICAL — lint buildup is a fire hazard (2,900 house fires/year per NFPA) and reduces dryer life by forcing longer, hotter cycles.",
    },
    costRange: {
      replacementLow: 400,
      replacementHigh: 1200,
      replacementMedian: 750,
      laborPercent: 10,
      year: 2025,
      notes: "Requires 240V outlet. 30A dedicated circuit. Delivery usually included.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.95, reason: "Humid air makes drying less efficient — longer run times" },
      hotDry: { scaleMultiplier: 1.05, reason: "Dry air helps drying efficiency" },
      coldHarsh: { scaleMultiplier: 1.0, reason: "Indoor appliance" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 0.95, reason: "Humid air reduces efficiency" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    warrantyCoverage: {
      typicalPartsYears: 1,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Standard 1-year. Speed Queen 3-5 years. Extended warranties worth considering on premium models.",
    },
    criticality: "medium" as const,
    tags: ["appliances", "laundry", "fire_safety", "vent_cleaning"],
  },
  {
    key: "water_heater_expansion_tank",
    systemCategory: "plumbing",
    subsystem: "water_supply",
    name: "Thermal Expansion Tank",
    description: "Small pressurized tank on the cold water line near the water heater that absorbs pressure increases from thermal expansion. Required by code in most closed water systems.",
    commonBrands: ["Watts", "Amtrol", "A.O. Smith", "Flexcon"],
    weibull: {
      shape: 3.5,
      scale: 7.0,
      medianLifespan: 6.5,
      p10Life: 3.5,
      p90Life: 9.0,
      dataSource: "Manufacturer data, plumbing contractor records",
      notes: "Internal rubber bladder fails (waterlogged). When it fails, the TPR valve starts dripping or water pressure spikes damage fixtures. Easy to test: tap on it — hollow ring means air charge intact, dull thud means waterlogged (replace). Short life for a code-required component — needs proactive replacement.",
    },
    costRange: {
      replacementLow: 100,
      replacementHigh: 300,
      replacementMedian: 175,
      laborPercent: 45,
      year: 2025,
      notes: "Tank $30-$60. Plumber install: $75-$200. DIY-friendly for handy homeowners.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.90, reason: "High water temps from warm supply and attic-mounted heaters accelerate bladder degradation" },
      hotDry: { scaleMultiplier: 0.85, reason: "High water temps plus hard water sediment in tank" },
      coldHarsh: { scaleMultiplier: 1.0, reason: "Standard conditions" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 0.95, reason: "Standard" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "high" as const,
    tags: ["plumbing", "water_heater", "code_required", "short_life", "proactive_replace"],
  },

  // ============================================================
  // FIRE SAFETY
  // ============================================================
  {
    key: "smoke_detector",
    systemCategory: "fire_safety",
    subsystem: "smoke_detection",
    name: "Smoke Detector / Alarm",
    description: "Ionization, photoelectric, or dual-sensor smoke detector. Battery or hardwired with battery backup.",
    commonBrands: ["First Alert", "Kidde", "Nest Protect", "X-Sense"],
    weibull: {
      shape: 5.0,
      scale: 10.5,
      medianLifespan: 10.0,
      p10Life: 7.5,
      p90Life: 12.5,
      dataSource: "NFPA, UL listing requirements, manufacturer data",
      notes: "10-year hard life limit per NFPA 72 and manufacturer specifications. Sensor sensitivity degrades with age. Must be replaced at 10 years regardless of apparent function — the manufacture date is printed on the back. Sealed 10-year lithium battery units eliminate low-battery chirps.",
    },
    costRange: {
      replacementLow: 20,
      replacementHigh: 60,
      replacementMedian: 35,
      laborPercent: 25,
      year: 2025,
      notes: "Per unit. Homes need 1 per bedroom + 1 per floor + 1 per hallway outside bedrooms. Typical home: 5-8 units. Smart models (Nest Protect): $100-$130 each.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.92, reason: "Humidity can cause false alarms and sensor degradation" },
      hotDry: { scaleMultiplier: 1.0, reason: "Standard" },
      coldHarsh: { scaleMultiplier: 1.0, reason: "Standard" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 0.95, reason: "Moisture" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "battery",
    criticality: "critical" as const,
    tags: ["fire_safety", "smoke", "code_required", "10_year_replacement", "every_home"],
  },
  {
    key: "co_detector",
    systemCategory: "fire_safety",
    subsystem: "co_detection",
    name: "Carbon Monoxide Detector",
    description: "Electrochemical sensor detecting CO gas from combustion appliances (furnace, water heater, fireplace, garage). Required in homes with fuel-burning equipment.",
    commonBrands: ["First Alert", "Kidde", "Nest Protect", "X-Sense"],
    weibull: {
      shape: 4.5,
      scale: 7.5,
      medianLifespan: 7.0,
      p10Life: 5.0,
      p90Life: 9.0,
      dataSource: "UL listing data, manufacturer specifications",
      notes: "5-7 year life for most CO sensors. Shorter than smoke detectors. Electrochemical sensors degrade faster. Combination smoke/CO units must be replaced at the shorter interval. End-of-life chirp pattern is different from low-battery — check manufacturer instructions.",
    },
    costRange: {
      replacementLow: 20,
      replacementHigh: 50,
      replacementMedian: 35,
      laborPercent: 20,
      year: 2025,
      notes: "Per unit. Required near every sleeping area and on every level with fuel-burning appliances. Combo smoke/CO units are most cost-effective.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.90, reason: "Humidity accelerates sensor degradation" },
      hotDry: { scaleMultiplier: 1.0, reason: "Standard" },
      coldHarsh: { scaleMultiplier: 0.95, reason: "More critical in cold climates — furnaces run constantly" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 0.92, reason: "Moisture" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "battery",
    criticality: "critical" as const,
    tags: ["fire_safety", "co", "code_required", "combustion", "every_home"],
  },

  // ============================================================
  // GARAGE
  // ============================================================
  {
    key: "garage_door_opener",
    systemCategory: "garage",
    subsystem: "openers",
    name: "Garage Door Opener",
    description: "Motorized garage door opener — chain drive, belt drive, or screw drive. Includes remote, wall button, and safety sensors.",
    commonBrands: ["LiftMaster (Chamberlain)", "Genie", "Craftsman", "Linear", "Overhead Door"],
    weibull: {
      shape: 2.8,
      scale: 14.0,
      medianLifespan: 12.5,
      p10Life: 6.5,
      p90Life: 18.5,
      dataSource: "Manufacturer data, garage door contractor records",
      notes: "Measured in cycles more than years (10,000-15,000 cycles typical). Belt drive models quieter and slightly longer life than chain drive. Gear and sprocket assembly is the most common wear point. Smart openers with WiFi: shorter life due to electronics. Safety sensor misalignment is the most common service call.",
    },
    costRange: {
      replacementLow: 300,
      replacementHigh: 700,
      replacementMedian: 450,
      laborPercent: 40,
      year: 2025,
      notes: "Opener unit $150-$400. Installation includes rail, safety sensors, remotes, and wall button. Smart models (LiftMaster myQ): $250-$500 unit.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.88, reason: "Unconditioned garage means humidity exposure on electronics and motor. Salt air in coastal areas." },
      hotDry: { scaleMultiplier: 0.95, reason: "Dust on rails and gears" },
      coldHarsh: { scaleMultiplier: 0.90, reason: "Motor works harder in cold. Grease stiffens." },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 0.82, reason: "Salt air corrosion on all metal components" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    warrantyCoverage: {
      typicalPartsYears: 4,
      typicalLaborYears: 1,
      extendedAvailable: false,
      notes: "LiftMaster: lifetime motor, 5-year parts, 1-year accessories.",
    },
    criticality: "medium" as const,
    tags: ["garage", "convenience", "security", "daily_use"],
  },
  {
    key: "garage_door",
    systemCategory: "garage",
    subsystem: "doors",
    name: "Garage Door",
    description: "Sectional overhead garage door. Steel, aluminum, wood, or composite. Insulated or non-insulated. Single or double-car.",
    commonBrands: ["Clopay", "Amarr", "Wayne Dalton", "CHI", "Overhead Door"],
    weibull: {
      shape: 3.5,
      scale: 28.0,
      medianLifespan: 25.5,
      p10Life: 14.5,
      p90Life: 35.0,
      dataSource: "IDA (International Door Association) data, manufacturer data",
      notes: "Door panels last 25-30+ years (steel). SPRINGS are the consumable: torsion springs have 10,000-20,000 cycle life (7-14 years of typical use). Spring replacement is the most common and dangerous garage door repair — high tension, professional recommended. Insulated doors R-value 6-18.",
    },
    costRange: {
      replacementLow: 1500,
      replacementHigh: 5000,
      replacementMedian: 2800,
      laborPercent: 40,
      year: 2025,
      notes: "Double-car insulated steel door. Premium carriage-style: $4000-$8000. Spring replacement only: $200-$400.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.85, reason: "Salt air, humidity on springs and hardware, wind load from storms. Wind-rated doors required in hurricane zones." },
      hotDry: { scaleMultiplier: 1.0, reason: "UV fading on paint but minimal mechanical impact" },
      coldHarsh: { scaleMultiplier: 0.90, reason: "Cold-brittle springs, ice on seals, road salt corrosion" },
      coldModerate: { scaleMultiplier: 0.95, reason: "Standard" },
      marine: { scaleMultiplier: 0.80, reason: "Aggressive salt corrosion on springs, hardware, and tracks" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "medium" as const,
    tags: ["garage", "curb_appeal", "insulation", "wind_rated", "springs"],
  },

  // ============================================================
  // SEPTIC & WELL
  // ============================================================
  {
    key: "septic_tank",
    systemCategory: "septic_well",
    subsystem: "septic",
    name: "Septic Tank",
    description: "Underground wastewater treatment tank (concrete, fiberglass, or polyethylene). Receives all household sewage and separates solids from liquid effluent.",
    commonBrands: ["Infiltrator", "Norwesco", "Orenco", "Custom concrete (local)"],
    weibull: {
      shape: 3.5,
      scale: 35.0,
      medianLifespan: 32.0,
      p10Life: 18.5,
      p90Life: 44.0,
      dataSource: "EPA septic system studies, county health department records, septic contractor data",
      notes: "Concrete tanks last 30-40+ years but baffles and lids deteriorate sooner. Fiberglass/poly: 30+ years. Regular pumping (every 3-5 years) is essential — without it, solids overflow into drain field and destroy it ($10K-$30K replacement). Tank inspection during pumping reveals baffle condition.",
    },
    costRange: {
      replacementLow: 3000,
      replacementHigh: 8000,
      replacementMedian: 5000,
      laborPercent: 60,
      year: 2025,
      notes: "Tank only. New complete system (tank + drain field): $10K-$30K. Perc testing and permits add $500-$2000.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.90, reason: "High water table affects tank structural integrity. Acidic soil in some areas corrodes concrete faster." },
      hotDry: { scaleMultiplier: 1.0, reason: "Dry soil is favorable for septic systems" },
      coldHarsh: { scaleMultiplier: 0.88, reason: "Deep frost line means deeper installation. Frost heave on tanks." },
      coldModerate: { scaleMultiplier: 0.95, reason: "Standard" },
      marine: { scaleMultiplier: 0.85, reason: "Saltwater intrusion in coastal areas. High water table." },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "critical" as const,
    tags: ["septic", "wastewater", "pumping_required", "rural"],
  },
  {
    key: "well_pump_submersible",
    systemCategory: "septic_well",
    subsystem: "well",
    name: "Well Pump — Submersible",
    description: "Submersible electric pump installed inside the well casing, below the water level. Pushes water up to the pressure tank.",
    commonBrands: ["Grundfos", "Franklin Electric", "Goulds (Xylem)", "Pentair (Myers, Sta-Rite)"],
    weibull: {
      shape: 3.0,
      scale: 13.0,
      medianLifespan: 12.0,
      p10Life: 6.5,
      p90Life: 17.5,
      dataSource: "Pump manufacturer data, well drilling contractor records, Groundwater Association data",
      notes: "Motor failure in a sealed submersible pump requires pulling the entire pump from the well ($1500-$3000+ just for the pull/reset). Pump life depends heavily on water quality — sand and sediment are killers. Lightning strike on the well circuit is a common failure cause in the Gulf Coast. Always pair with a surge protector.",
    },
    costRange: {
      replacementLow: 1500,
      replacementHigh: 4000,
      replacementMedian: 2500,
      laborPercent: 55,
      year: 2025,
      notes: "Includes pump pull, new pump, drop pipe, pitless adapter check. Deep wells (200+ feet) cost more. Well contractor + electrician.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.85, reason: "Lightning damage, high water table cycling, sand in shallow wells. Very common in rural Gulf Coast/Florida." },
      hotDry: { scaleMultiplier: 0.80, reason: "Deep wells, sand/sediment, mineral-heavy water, heavy demand for irrigation" },
      coldHarsh: { scaleMultiplier: 0.95, reason: "Well insulation critical for pitless adapter. Otherwise protected underground." },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 0.88, reason: "Saltwater intrusion risk in coastal wells" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    typicalCapacities: ["1/2 HP", "3/4 HP", "1 HP", "1.5 HP", "2 HP"],
    warrantyCoverage: {
      typicalPartsYears: 5,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Grundfos and Franklin Electric offer industry-leading warranties. Labor warranty important — pump pull is expensive.",
    },
    criticality: "critical" as const,
    tags: ["well", "water_supply", "rural", "lightning_risk", "pump_pull"],
  },
  {
    key: "pressure_tank",
    systemCategory: "septic_well",
    subsystem: "pressure_system",
    name: "Well Pressure Tank",
    description: "Pressurized water storage tank that maintains water pressure between pump cycles. Bladder or diaphragm type.",
    commonBrands: ["Well-X-Trol (Amtrol)", "Flexcon", "Pentair", "Goulds"],
    weibull: {
      shape: 3.0,
      scale: 10.0,
      medianLifespan: 9.0,
      p10Life: 5.0,
      p90Life: 13.5,
      dataSource: "Manufacturer data, well contractor records",
      notes: "Internal bladder failure causes waterlogging and rapid pump cycling (pump short-cycles = pump death). Easy to test: check air pressure with tire gauge on Schrader valve. Should match pump cut-in pressure (typically 28-38 PSI). Waterlogged tank is the #1 cause of premature well pump failure.",
    },
    costRange: {
      replacementLow: 300,
      replacementHigh: 800,
      replacementMedian: 500,
      laborPercent: 40,
      year: 2025,
      notes: "Tank $150-$400 depending on size. Larger tanks (80+ gallon) reduce pump cycles and extend pump life. Worth the upgrade.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.90, reason: "Warm water and minerals accelerate bladder degradation" },
      hotDry: { scaleMultiplier: 0.85, reason: "Hard water and sediment" },
      coldHarsh: { scaleMultiplier: 0.95, reason: "Standard if indoors/insulated" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 0.90, reason: "Water quality" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "high" as const,
    tags: ["well", "pressure", "bladder", "pump_protection"],
  },
];

export const seed = internalMutation({
  handler: async (ctx) => {
    let count = 0;
    for (const comp of components) {
      const existing = await ctx.db
        .query("componentTemplates")
        .withIndex("by_key", (q) => q.eq("key", comp.key))
        .first();
      if (!existing) {
        await ctx.db.insert("componentTemplates", comp);
        count++;
      }
    }
    console.log(`Seeded ${count} electrical, roofing, appliance, and remaining component templates`);
  },
});
