import { internalMutation } from "../_generated/server";

const components = [
  // ============================================================
  // WATER HEATING — TANK
  // ============================================================
  {
    key: "water_heater_tank_gas",
    systemCategory: "water_heating",
    subsystem: "tank",
    name: "Water Heater — Tank, Gas",
    description: "Conventional storage tank water heater fired by natural gas or propane. 30-80 gallon capacity. Most common water heater in US homes.",
    commonBrands: ["Rheem", "A.O. Smith", "Bradford White", "State", "Kenmore", "Whirlpool"],
    weibull: {
      shape: 4.2,
      scale: 12.5,
      medianLifespan: 11.5,
      p10Life: 7.0,
      p90Life: 15.5,
      dataSource: "ASHRAE, manufacturer warranty claims, plumbing contractor service records, NAHI home inspection data",
      notes: "High shape = tight clustering around median life. Tank corrosion (anode rod depletion) is primary failure mode — very predictable. Hard water and high-use households shorten life. Sacrificial anode inspection/replacement at year 4-5 can add 3-5 years.",
    },
    costRange: {
      replacementLow: 1200,
      replacementHigh: 2800,
      replacementMedian: 1800,
      laborPercent: 45,
      year: 2025,
      notes: "40-50 gallon standard. Includes TPR valve, discharge pipe, gas connection, venting. Expansion tank adds $200-$400 where required.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.88, reason: "High humidity in unconditioned spaces accelerates exterior corrosion. Warm inlet water temp reduces thermal cycling but high usage from showers." },
      hotDry: { scaleMultiplier: 0.82, reason: "Hard water in the Southwest is the #1 life reducer. Sediment accumulation and anode rod consumption accelerated by 30-50%." },
      coldHarsh: { scaleMultiplier: 1.05, reason: "Cold inlet water means more thermal cycling but less sediment activity. Well-maintained units last longer." },
      coldModerate: { scaleMultiplier: 1.0, reason: "Moderate conditions" },
      marine: { scaleMultiplier: 0.85, reason: "Salt air in unconditioned spaces plus moderate water hardness" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline region" },
    },
    efficiencyRatings: {
      metric: "UEF (Uniform Energy Factor)",
      minimumCode: 0.58,
      goodRating: 0.65,
      excellentRating: 0.70,
      notes: "UEF replaced EF in 2015. Condensing gas tanks reach 0.80+ UEF. ENERGY STAR requires UEF ≥ 0.64 for gas tank.",
    },
    fuelType: "natural_gas",
    typicalCapacities: ["30 gallon", "40 gallon", "50 gallon", "65 gallon", "75 gallon"],
    warrantyCoverage: {
      typicalPartsYears: 6,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Tank warranty is the key number: 6-year standard, 9-year and 12-year available at higher price points. Longer warranty units have larger anode rods.",
    },
    criticality: "high" as const,
    tags: ["water_heating", "gas", "tank", "common", "anode_rod"],
  },
  {
    key: "water_heater_tank_electric",
    systemCategory: "water_heating",
    subsystem: "tank",
    name: "Water Heater — Tank, Electric",
    description: "Conventional storage tank water heater using one or two electric resistance heating elements. 30-80 gallon capacity.",
    commonBrands: ["Rheem", "A.O. Smith", "Bradford White", "State", "Kenmore", "GE"],
    weibull: {
      shape: 3.8,
      scale: 13.0,
      medianLifespan: 12.0,
      p10Life: 7.0,
      p90Life: 16.5,
      dataSource: "ASHRAE, manufacturer data, plumbing contractor records",
      notes: "Slightly longer average life than gas due to fewer components and no combustion byproducts inside the tank. Lower element replacement can extend life by 2-3 years. Anode rod depletion is still the primary tank failure mode.",
    },
    costRange: {
      replacementLow: 800,
      replacementHigh: 2200,
      replacementMedian: 1400,
      laborPercent: 40,
      year: 2025,
      notes: "Lower equipment cost than gas. No venting required. May need electrical circuit upgrade for larger units.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.88, reason: "Same corrosion concerns as gas tanks in humid unconditioned spaces" },
      hotDry: { scaleMultiplier: 0.80, reason: "Hard water sediment and element scale buildup. Elements may need replacement every 3-5 years." },
      coldHarsh: { scaleMultiplier: 1.03, reason: "Cold inlet water, less sediment activity" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 0.85, reason: "Salt air corrosion on exterior" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    typicalCapacities: ["30 gallon", "40 gallon", "50 gallon", "66 gallon", "80 gallon"],
    warrantyCoverage: {
      typicalPartsYears: 6,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Same tank warranty tiers as gas: 6, 9, 12-year. Elements are separately warrantied, typically 1 year.",
    },
    criticality: "high" as const,
    tags: ["water_heating", "electric", "tank", "common"],
  },
  {
    key: "water_heater_tankless_gas",
    systemCategory: "water_heating",
    subsystem: "tankless",
    name: "Water Heater — Tankless, Gas",
    description: "On-demand gas water heater that heats water only as it flows through the unit. No storage tank. Continuous hot water supply.",
    commonBrands: ["Rinnai", "Navien", "Noritz", "Rheem", "Takagi", "A.O. Smith"],
    weibull: {
      shape: 3.5,
      scale: 22.0,
      medianLifespan: 20.0,
      p10Life: 11.5,
      p90Life: 28.5,
      dataSource: "Manufacturer data, Japanese market longevity studies (30+ year deployment), US service records",
      notes: "20+ year life is achievable WITH regular descaling maintenance. Without descaling in hard water areas, heat exchanger can fail in 5-8 years. Maintenance compliance is the dominant life factor, more so than any other residential component.",
    },
    costRange: {
      replacementLow: 2500,
      replacementHigh: 5500,
      replacementMedian: 3800,
      laborPercent: 45,
      year: 2025,
      notes: "Gas line sizing upgrade sometimes needed ($300-$1000). Condensing models require condensate drain. Venting: direct-vent PVC for condensing, stainless for non-condensing.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.90, reason: "Warm inlet water is good (less thermal shock) but hard water in some areas requires diligent descaling" },
      hotDry: { scaleMultiplier: 0.70, reason: "HARD WATER IS THE KILLER. Southwest well water and municipal water with 200+ ppm hardness destroys heat exchangers without annual or semi-annual descaling." },
      coldHarsh: { scaleMultiplier: 0.85, reason: "Cold inlet water means maximum temperature rise. Unit works hardest. Freeze protection draws standby power." },
      coldModerate: { scaleMultiplier: 0.95, reason: "Moderate inlet temps, moderate demand" },
      marine: { scaleMultiplier: 0.88, reason: "Salt air on exterior vent termination" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    efficiencyRatings: {
      metric: "UEF",
      minimumCode: 0.82,
      goodRating: 0.90,
      excellentRating: 0.96,
      notes: "Non-condensing: 0.82-0.85 UEF. Condensing: 0.92-0.97 UEF. Condensing models are worth the premium in most applications.",
    },
    fuelType: "natural_gas",
    typicalCapacities: ["6.5 GPM", "8 GPM", "9.5 GPM", "11 GPM"],
    warrantyCoverage: {
      typicalPartsYears: 5,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Heat exchanger typically 12-15 year warranty (varies by brand). Navien 15-year heat exchanger, Rinnai 12-year. Parts 5-year.",
    },
    criticality: "high" as const,
    tags: ["water_heating", "gas", "tankless", "on_demand", "descaling_required"],
  },
  {
    key: "water_heater_heat_pump",
    systemCategory: "water_heating",
    subsystem: "heat_pump",
    name: "Water Heater — Heat Pump (Hybrid)",
    description: "Electric water heater that uses a heat pump compressor to extract heat from surrounding air, 2-3x more efficient than standard electric. Has backup resistance elements.",
    commonBrands: ["Rheem (ProTerra)", "A.O. Smith (Voltex)", "Bradford White (AeroTherm)", "GE GeoSpring", "Stiebel Eltron"],
    weibull: {
      shape: 3.0,
      scale: 14.0,
      medianLifespan: 12.5,
      p10Life: 6.5,
      p90Life: 18.5,
      dataSource: "DOE heat pump water heater studies, manufacturer data, energy efficiency program monitoring",
      notes: "Compressor has separate failure profile from tank. Compressor: 10-15 year life. Tank: 12-15 year life. Whichever fails first determines unit life. Cooler ambient air (below 40°F) forces fallback to resistance heating. Needs 700+ cubic feet of air space around unit.",
    },
    costRange: {
      replacementLow: 1800,
      replacementHigh: 4000,
      replacementMedian: 2800,
      laborPercent: 40,
      year: 2025,
      notes: "Equipment $1200-$2500. Condensate drain required (produces significant condensation). May need electrical upgrade to 30A dedicated circuit. Federal 25C tax credit up to $2000 applies.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 1.05, reason: "IDEAL climate. Warm ambient air maximizes heat pump efficiency. Also dehumidifies the space it's in — double benefit in Gulf Coast garages/utility rooms." },
      hotDry: { scaleMultiplier: 1.0, reason: "Warm air is good for efficiency. Hard water still affects tank life." },
      coldHarsh: { scaleMultiplier: 0.80, reason: "Cold ambient air reduces heat pump efficiency. Unit falls back to resistance heating frequently. Cools surrounding space — problematic in conditioned garages in winter." },
      coldModerate: { scaleMultiplier: 0.92, reason: "Works well spring-fall, may use resistance backup in deep winter" },
      marine: { scaleMultiplier: 0.95, reason: "Mild temps are good, but cool garages in PNW reduce winter efficiency" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    efficiencyRatings: {
      metric: "UEF",
      minimumCode: 2.0,
      goodRating: 3.0,
      excellentRating: 3.75,
      notes: "UEF 3.5+ means unit is 3.5x more efficient than standard electric. Annual savings of $200-$500 vs standard electric. ENERGY STAR requires UEF ≥ 2.20.",
    },
    fuelType: "electric",
    typicalCapacities: ["50 gallon", "65 gallon", "80 gallon"],
    warrantyCoverage: {
      typicalPartsYears: 6,
      typicalLaborYears: 1,
      extendedAvailable: true,
      notes: "Rheem ProTerra offers 10-year tank and parts warranty. Compressor warranty tracks tank warranty.",
    },
    criticality: "high" as const,
    tags: ["water_heating", "electric", "heat_pump", "high_efficiency", "incentives", "recommended"],
  },

  // ============================================================
  // PLUMBING — WATER SUPPLY
  // ============================================================
  {
    key: "copper_supply_piping",
    systemCategory: "plumbing",
    subsystem: "water_supply",
    name: "Copper Water Supply Piping",
    description: "Copper pipe (Type L or M) for domestic water distribution. Industry standard for decades. Soldered or press-fit joints.",
    commonBrands: ["Mueller", "Cerro", "Cambridge-Lee", "?"/* no dominant consumer brand */],
    weibull: {
      shape: 5.0,
      scale: 55.0,
      medianLifespan: 52.0,
      p10Life: 37.0,
      p90Life: 65.0,
      dataSource: "Copper Development Association studies, municipal water system data, home inspection records",
      notes: "Very high shape = predictable aging. 50+ year life in most conditions. Pinhole leaks from aggressive water chemistry (low pH, high chloride) are the primary failure mode. Type M (thinner wall) has shorter life than Type L.",
    },
    costRange: {
      replacementLow: 5000,
      replacementHigh: 15000,
      replacementMedian: 9000,
      laborPercent: 70,
      year: 2025,
      notes: "Full repipe cost for typical 3BR/2BA home. Labor dominates — wall access, patching, fixture reconnection. Partial repair/replacement much cheaper.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.90, reason: "Warm water, potential for aggressive water chemistry, condensation on exposed cold lines" },
      hotDry: { scaleMultiplier: 0.85, reason: "Hard water and high mineral content in Southwest accelerates pinhole leak development" },
      coldHarsh: { scaleMultiplier: 0.80, reason: "Freeze-thaw is the biggest risk. Burst pipe damage from single freeze event can be catastrophic." },
      coldModerate: { scaleMultiplier: 0.95, reason: "Moderate freeze risk" },
      marine: { scaleMultiplier: 0.92, reason: "Slightly aggressive water chemistry in some PNW systems" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "high" as const,
    tags: ["piping", "water_supply", "long_life", "repipe"],
  },
  {
    key: "pex_supply_piping",
    systemCategory: "plumbing",
    subsystem: "water_supply",
    name: "PEX Water Supply Piping",
    description: "Cross-linked polyethylene (PEX-A, PEX-B, or PEX-C) flexible tubing for water distribution. Modern standard for new construction and repiping.",
    commonBrands: ["Uponor (PEX-A)", "SharkBite", "Viega", "Zurn", "Watts"],
    weibull: {
      shape: 4.5,
      scale: 45.0,
      medianLifespan: 42.0,
      p10Life: 28.0,
      p90Life: 55.0,
      dataSource: "ASTM accelerated aging tests, European deployment data (40+ years), manufacturer claims",
      notes: "PEX has been used in Europe since the 1970s with 40+ year track records. US deployment is shorter but accelerated testing supports 40-50+ year life. UV exposure degrades PEX — must not be exposed to sunlight. Fitting type matters: expansion fittings (PEX-A) have best long-term track record.",
    },
    costRange: {
      replacementLow: 3500,
      replacementHigh: 10000,
      replacementMedian: 6500,
      laborPercent: 65,
      year: 2025,
      notes: "Full repipe. Less than copper due to faster installation (flexible, fewer fittings). PEX-A expansion fittings most reliable but most expensive.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 1.0, reason: "PEX handles warm water well. Not affected by humidity." },
      hotDry: { scaleMultiplier: 0.95, reason: "Extremely hot attics (150°F+) can approach PEX temperature limits. Insulation recommended." },
      coldHarsh: { scaleMultiplier: 1.10, reason: "PEX is freeze-resistant — can expand and recover from freezing better than rigid pipe. Major advantage over copper." },
      coldModerate: { scaleMultiplier: 1.05, reason: "Good freeze tolerance" },
      marine: { scaleMultiplier: 1.0, reason: "Not affected by salt air" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "high" as const,
    tags: ["piping", "water_supply", "modern", "repipe", "freeze_resistant"],
  },
  {
    key: "galvanized_supply_piping",
    systemCategory: "plumbing",
    subsystem: "water_supply",
    name: "Galvanized Steel Water Supply Piping",
    description: "Zinc-coated steel pipe used extensively in pre-1970 construction. Known for internal corrosion and restricted flow over time.",
    commonBrands: ["Various — no longer manufactured for residential supply"],
    weibull: {
      shape: 5.5,
      scale: 50.0,
      medianLifespan: 47.0,
      p10Life: 35.0,
      p90Life: 58.0,
      dataSource: "AWWA studies, municipal water data, home inspection records spanning decades",
      notes: "NOT a positive lifespan story. While the pipe may 'last' 40-60 years, internal corrosion causes restricted flow, discolored water, and eventually pinhole leaks starting at 25-35 years. Should be proactively replaced if present — it's a ticking clock. Any remaining galvanized supply piping in a home is already past its best-by date.",
    },
    costRange: {
      replacementLow: 5000,
      replacementHigh: 15000,
      replacementMedian: 8500,
      laborPercent: 65,
      year: 2025,
      notes: "Repipe to PEX or copper. Cost depends on accessibility. Slab homes more expensive (overhead reroute or tunneling).",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.80, reason: "Warm water accelerates internal corrosion. Aggressive water chemistry compounds the problem." },
      hotDry: { scaleMultiplier: 0.75, reason: "Hard water dramatically accelerates internal corrosion and buildup. REPIPE IMMEDIATELY if galvanized is found." },
      coldHarsh: { scaleMultiplier: 0.90, reason: "Cold water is slightly less aggressive but freeze risk adds failure mode" },
      coldModerate: { scaleMultiplier: 0.95, reason: "Moderate conditions" },
      marine: { scaleMultiplier: 0.78, reason: "Aggressive conditions inside and out" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "critical" as const,
    tags: ["piping", "water_supply", "legacy", "replacement_urgent", "pre_1970"],
  },
  {
    key: "main_water_shutoff",
    systemCategory: "plumbing",
    subsystem: "water_supply",
    name: "Main Water Shutoff Valve",
    description: "Primary shutoff valve controlling all water to the home. Gate valve, ball valve, or globe valve. Located near where the water main enters the home.",
    commonBrands: ["Watts", "SharkBite", "Apollo", "Nibco", "Mueller"],
    weibull: {
      shape: 2.5,
      scale: 20.0,
      medianLifespan: 17.5,
      p10Life: 7.5,
      p90Life: 28.0,
      dataSource: "Plumbing contractor records, home inspection data",
      notes: "Gate valves are the most common and most problematic — they seize if not operated regularly and fail to fully shut off. Ball valves are far more reliable. Replacement of a seized gate valve with a ball valve is one of the highest-value plumbing upgrades. EVERY homeowner should know where this is and verify it works.",
    },
    costRange: {
      replacementLow: 200,
      replacementHigh: 600,
      replacementMedian: 350,
      laborPercent: 65,
      year: 2025,
      notes: "Valve itself is $20-$60. Labor for cutting, fitting, and sometimes coordinating with water utility to shut off at the meter.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.90, reason: "Mineral buildup and humidity. Outdoor meter boxes flood in heavy rain." },
      hotDry: { scaleMultiplier: 0.85, reason: "Hard water scale seizes gate valves faster" },
      coldHarsh: { scaleMultiplier: 0.80, reason: "Freeze risk on valves near exterior walls. Critical that this valve works for winterization." },
      coldModerate: { scaleMultiplier: 0.95, reason: "Moderate conditions" },
      marine: { scaleMultiplier: 0.88, reason: "Corrosion on valve body" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "critical" as const,
    tags: ["water_supply", "shutoff", "emergency_preparedness", "every_home"],
  },
  {
    key: "pressure_regulator",
    systemCategory: "plumbing",
    subsystem: "water_supply",
    name: "Water Pressure Regulator (PRV)",
    description: "Reduces incoming municipal water pressure to a safe level (typically 50-70 PSI). Prevents damage to fixtures, pipes, and appliances from excessive pressure.",
    commonBrands: ["Watts", "Zurn Wilkins", "Apollo", "Cash Acme"],
    weibull: {
      shape: 3.0,
      scale: 10.0,
      medianLifespan: 9.0,
      p10Life: 5.0,
      p90Life: 13.5,
      dataSource: "Manufacturer data, plumbing contractor records",
      notes: "Internal rubber diaphragm and spring wear over time, causing creep (pressure slowly rises) or failure to regulate. Should be tested with a pressure gauge annually. Municipal pressure can be 80-150+ PSI — unregulated, this destroys washing machine hoses, ice maker lines, and toilet fill valves.",
    },
    costRange: {
      replacementLow: 250,
      replacementHigh: 600,
      replacementMedian: 400,
      laborPercent: 55,
      year: 2025,
      notes: "Valve $40-$80. Labor includes shutting off water, cutting pipe, and sometimes adding a pressure gauge (recommended).",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.92, reason: "High municipal pressure common in Gulf Coast systems" },
      hotDry: { scaleMultiplier: 0.85, reason: "Hard water deposits on diaphragm. High municipal pressure in desert cities." },
      coldHarsh: { scaleMultiplier: 0.95, reason: "Standard conditions" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 0.95, reason: "Standard conditions" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "high" as const,
    tags: ["water_supply", "pressure", "damage_prevention", "silent_killer"],
  },

  // ============================================================
  // PLUMBING — DWV (Drain-Waste-Vent)
  // ============================================================
  {
    key: "cast_iron_drain",
    systemCategory: "plumbing",
    subsystem: "dwv",
    name: "Cast Iron Drain/Waste/Vent Pipe",
    description: "Cast iron pipe used for drain, waste, and vent lines in pre-1980 construction. Heavy, durable, but subject to internal corrosion.",
    commonBrands: ["Charlotte Pipe", "Tyler Pipe", "Various foundries"],
    weibull: {
      shape: 4.0,
      scale: 55.0,
      medianLifespan: 50.0,
      p10Life: 33.0,
      p90Life: 66.0,
      dataSource: "Cast Iron Soil Pipe Institute data, municipal sewer studies, plumbing contractor records",
      notes: "50+ year life in good conditions. Horizontal runs fail before vertical. Bottom of horizontal pipes corrodes first (water/waste sits there). Hub-and-spigot joints with lead and oakum are the weakest points. Sewer camera inspection is the best assessment tool. Still functional in many 1960s-1970s homes but approaching end-of-life.",
    },
    costRange: {
      replacementLow: 4000,
      replacementHigh: 15000,
      replacementMedian: 8000,
      laborPercent: 70,
      year: 2025,
      notes: "Partial replacement (worst sections) $2000-$6000. Full DWV repipe $8000-$15000+. Slab homes cost more (tunneling or overhead reroute).",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.85, reason: "High moisture and acidic soil accelerate external corrosion. Hydrogen sulfide from warm sewer gas attacks interior." },
      hotDry: { scaleMultiplier: 1.0, reason: "Dry soil is gentle on exterior. Interior corrosion proceeds normally." },
      coldHarsh: { scaleMultiplier: 0.90, reason: "Freeze-thaw cycles stress joints. Road salt near foundation can accelerate exterior corrosion." },
      coldModerate: { scaleMultiplier: 0.95, reason: "Moderate conditions" },
      marine: { scaleMultiplier: 0.82, reason: "Salt environment inside and out" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "high" as const,
    tags: ["dwv", "drain", "legacy", "camera_inspection", "pre_1980"],
  },
  {
    key: "pvc_drain",
    systemCategory: "plumbing",
    subsystem: "dwv",
    name: "PVC Drain/Waste/Vent Pipe",
    description: "PVC (Schedule 40) drain, waste, and vent piping. Standard in all new construction since the 1980s. Solvent-welded joints.",
    commonBrands: ["Charlotte Pipe", "JM Eagle", "Ipex", "NIBCO"],
    weibull: {
      shape: 5.0,
      scale: 65.0,
      medianLifespan: 61.0,
      p10Life: 44.0,
      p90Life: 76.0,
      dataSource: "Uni-Bell PVC Pipe Association studies, manufacturer accelerated aging data",
      notes: "Extremely long life. Immune to corrosion (no metal). UV exposure degrades it (must not be used outdoors without protection). Joint failures from poor installation or ground movement are the primary failure mode. Chemical resistance is excellent. Most PVC drain pipe installed in the 1980s will last well into the 2050s.",
    },
    costRange: {
      replacementLow: 3000,
      replacementHigh: 10000,
      replacementMedian: 6000,
      laborPercent: 65,
      year: 2025,
      notes: "Full DWV replacement with PVC. Rarely needed except in cases of ground settlement, tree root intrusion, or improper original installation.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 1.0, reason: "PVC handles humidity and warm conditions well" },
      hotDry: { scaleMultiplier: 1.0, reason: "UV is only concern — buried/interior pipe unaffected" },
      coldHarsh: { scaleMultiplier: 0.95, reason: "PVC becomes more brittle in extreme cold, but underground/interior pipe is protected" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 1.0, reason: "Immune to salt corrosion" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "medium" as const,
    tags: ["dwv", "drain", "modern", "long_life"],
  },
  {
    key: "sewer_line_main",
    systemCategory: "plumbing",
    subsystem: "dwv",
    name: "Main Sewer Line (House to Street)",
    description: "Underground pipe connecting the home's drainage system to the municipal sewer or septic system. Typically 4\" diameter, 20-100+ feet long.",
    commonBrands: ["Various — material dependent (clay, cast iron, PVC, orangeburg)"],
    weibull: {
      shape: 3.0,
      scale: 50.0,
      medianLifespan: 45.0,
      p10Life: 22.0,
      p90Life: 65.0,
      dataSource: "Municipal sewer camera inspection data, plumbing contractor records, NASSCO pipeline assessment data",
      notes: "Wide spread due to multiple materials and conditions. Clay pipe (pre-1970): 50-60 years but tree root invasion is common. Orangeburg (1940s-1970s): 30-50 years, often collapsed. Cast iron: 50-75 years. PVC: 60-100+ years. Sewer camera inspection ($200-$400) is the only way to know actual condition.",
    },
    costRange: {
      replacementLow: 3000,
      replacementHigh: 15000,
      replacementMedian: 7500,
      laborPercent: 70,
      year: 2025,
      notes: "Trenchless (pipe bursting/lining): $4000-$10000. Traditional excavation: $3000-$15000 depending on length, depth, and landscaping damage. Trenchless avoids destroying the yard.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.85, reason: "Aggressive root growth year-round. Warm soil promotes root intrusion and pipe degradation." },
      hotDry: { scaleMultiplier: 0.90, reason: "Dry soil causes settlement. Roots seek sewer lines as only water source." },
      coldHarsh: { scaleMultiplier: 0.90, reason: "Deep frost line means deeper pipe — more expensive repair. Frost heave can crack joints." },
      coldModerate: { scaleMultiplier: 0.95, reason: "Moderate root growth and soil movement" },
      marine: { scaleMultiplier: 0.95, reason: "High water table can affect pipe joints" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "critical" as const,
    tags: ["dwv", "sewer", "underground", "camera_inspection", "tree_roots", "expensive"],
  },

  // ============================================================
  // PLUMBING — FIXTURES
  // ============================================================
  {
    key: "toilet",
    systemCategory: "plumbing",
    subsystem: "fixtures",
    name: "Toilet",
    description: "Gravity-flush toilet with tank and bowl. Porcelain fixture with internal flush valve, fill valve, flapper, and wax ring seal.",
    commonBrands: ["TOTO", "Kohler", "American Standard", "Gerber", "Mansfield", "Delta"],
    weibull: {
      shape: 2.0,
      scale: 30.0,
      medianLifespan: 25.0,
      p10Life: 10.0,
      p90Life: 42.0,
      dataSource: "Manufacturer data, plumbing contractor records",
      notes: "Porcelain body lasts 50+ years (effectively forever unless cracked). Internal components (flapper, fill valve, flush valve) are consumables that need replacement every 5-10 years. The 'lifespan' here represents useful life before full replacement is preferable to continued component replacement. Wax ring replacement needed if toilet is removed or develops base leak.",
    },
    costRange: {
      replacementLow: 300,
      replacementHigh: 800,
      replacementMedian: 500,
      laborPercent: 50,
      year: 2025,
      notes: "Toilet $120-$500. Installation includes wax ring, supply line, closet bolts. Premium toilets (TOTO Washlet) can reach $2000+.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.95, reason: "Condensation on tank in humid homes (tank sweating). Mineral buildup in warm water areas." },
      hotDry: { scaleMultiplier: 0.88, reason: "Hard water destroys fill valves and flappers faster. Mineral ring buildup." },
      coldHarsh: { scaleMultiplier: 1.0, reason: "Indoor fixture — minimal climate impact" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Indoor fixture" },
      marine: { scaleMultiplier: 1.0, reason: "Indoor fixture" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "none",
    typicalCapacities: ["1.28 GPF (WaterSense)", "1.6 GPF (standard)", "1.0 GPF (high efficiency)"],
    warrantyCoverage: {
      typicalPartsYears: 1,
      typicalLaborYears: 0,
      extendedAvailable: false,
      notes: "Porcelain body often has limited lifetime warranty. Internal components are consumables.",
    },
    criticality: "medium" as const,
    tags: ["fixtures", "bathroom", "water_efficiency", "common"],
  },
  {
    key: "faucet_kitchen",
    systemCategory: "plumbing",
    subsystem: "fixtures",
    name: "Kitchen Faucet",
    description: "Kitchen sink faucet with single or dual handle. May include pull-down sprayer, touchless activation, or filtered water dispenser.",
    commonBrands: ["Moen", "Delta", "Kohler", "Pfister", "Kraus", "Grohe", "American Standard"],
    weibull: {
      shape: 2.5,
      scale: 17.0,
      medianLifespan: 15.0,
      p10Life: 7.0,
      p90Life: 23.5,
      dataSource: "Manufacturer data, plumbing contractor records",
      notes: "Cartridge/valve failure causes dripping — repairable. Finish deterioration and sprayer hose failure are common in mid-range faucets. Premium brass-body faucets (Moen, Kohler, Delta) with ceramic disc cartridges last longest. Budget zinc-body faucets may fail in 5-8 years.",
    },
    costRange: {
      replacementLow: 200,
      replacementHigh: 700,
      replacementMedian: 400,
      laborPercent: 45,
      year: 2025,
      notes: "Faucet $80-$500. Installation includes supply line replacement. Under-sink access is the main labor factor.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.95, reason: "Mineral buildup on aerator and in cartridge" },
      hotDry: { scaleMultiplier: 0.82, reason: "Hard water destroys cartridges and causes premature finish damage" },
      coldHarsh: { scaleMultiplier: 1.0, reason: "Indoor fixture" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Indoor fixture" },
      marine: { scaleMultiplier: 0.95, reason: "Salt air can affect exterior finish" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "low" as const,
    tags: ["fixtures", "kitchen", "cosmetic", "daily_use"],
  },
  {
    key: "water_softener",
    systemCategory: "plumbing",
    subsystem: "water_treatment",
    name: "Water Softener (Ion Exchange)",
    description: "Whole-house water softener using ion exchange resin to remove calcium and magnesium hardness from water supply",
    commonBrands: ["Fleck", "Clack", "Kinetico", "Culligan", "Pentair", "GE", "Whirlpool"],
    weibull: {
      shape: 3.0,
      scale: 14.0,
      medianLifespan: 12.5,
      p10Life: 6.5,
      p90Life: 18.5,
      dataSource: "Water Quality Association data, manufacturer records, water treatment contractor data",
      notes: "Resin bed lasts 10-15 years. Control valve is the primary failure point (motor, seals, timer). Salt-based systems require ongoing salt purchases ($50-$100/month). Properly maintained units protect all downstream plumbing and appliances from hard water damage — ROI is excellent in hard water areas.",
    },
    costRange: {
      replacementLow: 800,
      replacementHigh: 3500,
      replacementMedian: 2000,
      laborPercent: 35,
      year: 2025,
      notes: "Equipment $500-$2500. Kinetico (non-electric) at premium. DIY installation possible for handy homeowners. Professional recommended for proper sizing.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 1.0, reason: "Moderate hardness in most Gulf Coast municipal water. Well water can be very hard." },
      hotDry: { scaleMultiplier: 0.85, reason: "Extreme hardness (200-500+ ppm) in Southwest means unit works much harder. Resin exhaustion faster." },
      coldHarsh: { scaleMultiplier: 1.05, reason: "Moderate hardness in many Great Lakes/Midwest areas" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 1.05, reason: "Generally softer water in PNW" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "medium" as const,
    tags: ["water_treatment", "hardness", "protection", "well_water"],
  },
  {
    key: "sump_pump",
    systemCategory: "plumbing",
    subsystem: "water_supply",
    name: "Sump Pump",
    description: "Submersible or pedestal pump in a sump pit that removes groundwater from beneath the foundation to prevent basement/crawlspace flooding",
    commonBrands: ["Zoeller", "Wayne", "Superior", "Liberty", "Little Giant"],
    weibull: {
      shape: 2.8,
      scale: 9.0,
      medianLifespan: 8.0,
      p10Life: 4.0,
      p90Life: 12.5,
      dataSource: "Manufacturer data, home inspection records, flood insurance claim data",
      notes: "Submersible pumps last 7-10 years. Pedestal pumps slightly longer. Float switch failure is most common issue. Battery backup systems essential — pump is useless during power outage (often coincides with flooding). Test monthly by pouring water into pit.",
    },
    costRange: {
      replacementLow: 300,
      replacementHigh: 1200,
      replacementMedian: 600,
      laborPercent: 40,
      year: 2025,
      notes: "Pump $100-$400. Battery backup system adds $300-$600. Professional installation includes check valve and discharge line verification.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.85, reason: "High water table means frequent cycling. More hours = shorter life." },
      hotDry: { scaleMultiplier: 1.20, reason: "Rarely needed in dry climates. Long life when present." },
      coldHarsh: { scaleMultiplier: 0.80, reason: "Critical equipment. Spring snowmelt flooding. Frozen discharge lines." },
      coldModerate: { scaleMultiplier: 0.90, reason: "Moderate use during wet seasons" },
      marine: { scaleMultiplier: 0.85, reason: "High rainfall, frequent cycling" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    criticality: "critical" as const,
    tags: ["water_management", "flood_prevention", "basement", "crawlspace", "battery_backup"],
  },
  {
    key: "garbage_disposal",
    systemCategory: "plumbing",
    subsystem: "fixtures",
    name: "Garbage Disposal",
    description: "In-sink food waste disposer mounted beneath kitchen sink. Grinds food waste for drainage. 1/3 to 1 HP motor.",
    commonBrands: ["InSinkErator", "Waste King", "Moen", "GE", "KitchenAid"],
    weibull: {
      shape: 2.8,
      scale: 11.0,
      medianLifespan: 10.0,
      p10Life: 5.0,
      p90Life: 15.0,
      dataSource: "Manufacturer data, appliance industry reports",
      notes: "Higher HP units (3/4, 1 HP) last longer than budget 1/3 HP models. Jamming and motor burnout are primary failures. Stainless steel grind chambers last longer than galvanized. InSinkErator Evolution series known for longevity.",
    },
    costRange: {
      replacementLow: 200,
      replacementHigh: 600,
      replacementMedian: 350,
      laborPercent: 40,
      year: 2025,
      notes: "Unit $80-$350. Plumber install includes electrical connection and drain hookup. Many homeowners DIY with basic tools.",
    },
    regionalAdjustments: {
      hotHumid: { scaleMultiplier: 0.95, reason: "Warm temperatures promote odor if not run regularly" },
      hotDry: { scaleMultiplier: 0.90, reason: "Hard water mineral buildup on grinding components" },
      coldHarsh: { scaleMultiplier: 1.0, reason: "Standard conditions" },
      coldModerate: { scaleMultiplier: 1.0, reason: "Standard" },
      marine: { scaleMultiplier: 0.95, reason: "Moisture environment" },
      mixed: { scaleMultiplier: 1.0, reason: "Baseline" },
    },
    fuelType: "electric",
    typicalCapacities: ["1/3 HP", "1/2 HP", "3/4 HP", "1 HP"],
    warrantyCoverage: {
      typicalPartsYears: 4,
      typicalLaborYears: 0,
      extendedAvailable: false,
      notes: "InSinkErator: 2-year (Badger) to 7-year (Evolution Excel). Premium models have the best warranty in the category.",
    },
    criticality: "low" as const,
    tags: ["fixtures", "kitchen", "convenience", "common"],
  },
];

export const seed = internalMutation({
  handler: async (ctx) => {
    let count = 0;
    for (const comp of components) {
      const existing = await ctx.db
        .query("componentTemplates")
        .withIndex("by_key", (q) => q.eq("key", comp.key))
        .first();
      if (!existing) {
        await ctx.db.insert("componentTemplates", comp);
        count++;
      }
    }
    console.log(`Seeded ${count} plumbing & water heating component templates`);
  },
});
